# Definitions of Functional Groups  {#sec-functional-groups}

## Introduction to functional groups {#sec-intro-functional-groups}

### Types of functional groups

Biological components are represented as **biomass pools** (most non-vertebrates), **age-structured biomass pools** (some invertebrates) or **age-structured groups** (vertebrates). These three group types are assigned according to the [GroupType]{style="color: orange;"} and [NumCohorts]{style="color: orange;"} parameters given in the *functional_groups.csv* file (@tbl-state-variables). Group types FISH, FISH_INVERT, SHARK, MAMMAL, BIRD, REPTILE are assigned to the fully age-structured groups with the number of age groups given by [NumCohorts]{style="color: orange;"}. Other groups are assigned to biomass pools. If [NumCohorts]{style="color: orange;"} for a biomass pool is >1 they will be assigned to an age-structured biomass pool. The age-structured biomass pools are similar to stanzas used in, for example, Ecosim and are used to allow for different juvenile and adult behaviour and parameters. All non-vertebrates that have [NumCohorts]{style="color: orange;"}=1 are assigned to simple biomass pools.

::: {.callout-caution}
**Can a non-vertebrate be modelled as an age-structured group?**

Six [GroupTypes]{style="color: orange;"} (FISH, FISH_INVERT, MAMMAL, SHARK, BIRD and REPTILE) are currently modelled as age-structured groups. If full age-structure is needed for a non-vertebrate, it should be set as one of these groups, most likely as FISH_INVERT or FISH. FISH_INVERT currently uses the same code as FISH, but the intent is to use it to represent a size rather than age-based model, which is a more typical representation for key invertebrates (such as exploited species). Note however that setting a group as FISH_INVERT or FISH would not call typical non-vertebrate routines (see below).
:::

Atlantis does not explicitly model sex, but represents an average individual. This means that all individuals in a biomass pool and an age cohort (or a genotype in a cohort, if multiple genotypes are modelled) are considered identical in terms of their reproductive output. This may require some caution in parameterisation, e.g. number of offspring per mammal individual.

### State variables tracked

#### Main model

In models that are based on N only (i.e. do not explicitly track P and C) the only state variable tracked for most biomass pools is N, but both N and Si fluxes are tracked for Si limited biomass pools, such as diatoms. The Si limited groups are identified from the *functional_groups.csv* file parameter [IsSiliconDep]{style="color: orange;"} (see below). In age-structured groups three variables are tracked for each age cohort: reserve N (RN), structural N (SN) and numbers (Num). In addition, fluxes in the water column and sediments are tracked through eight **inanimate pools**: ammonia (NH), nitrate (NO), dissolved silica (Si), detrital silica (DSi), dissolved oxygen (O2), dissolved organic nitrogen (DON), labile detritus (DL), and refractory detritus (DR). An additional inanimate pool, carrion (DC), is also required, though it is only dynamically used if the fisheries submodel is active; DC is then used to represent fisheries discards. State variables tracked for each group defined with the [GroupType]{style="color: orange;"} parameter in the *functional_groups.csv* file are listed (@tbl-state-variables).

#### Extended models

If the model also includes tracking of P and C ([trackAtomicRatio]{style="color: orange;"} is set to 1 in *run.prm*), then P and C pools are tracked for each functional group, together with N pools. Additional inanimate pools are for C and P are also required. If the model is of an estuary ([flagIsEstuary]{style="color: orange;"}=1 in *run.prm* file) a sediment (SED) inanimate pool is added for the water column. If the model tracks contaminants ([track_contaminants]{style="color: orange;"}=1 in *run.prm*) a separate pool is added for each contaminant for each nitrogen pool tracked, so that concentration of contaminants can be tracked throughout the entire food web. If the model spans polar regions ([flagIsPolar]{style="color: orange;"}=1 in *run.prm*) the model allows for 24 hours of night/daylight seasonally.

### Allocation of pools throughout the vertical dimension: water column, epibenthos and sediment

Atlantis models 3-5 explicit distribution types of organisms and inanimate pools through the model domain — **water column**, **epibenthic layer** and **sediments** are tracked in all models and **ice** and **land** may also optionally be included. The water column and **sediment** are modelled as three dimensional spaces (units of variables are in m^3^), whereas the epibenthic layer is two-dimensional (units in m^2^). Most organisms are restricted to one type, such as sediments (infaunal invertebrates identified with INF in GroupType name), epibenthic layer (epibenthic organisms, identified with EP in the GroupType name) or water column (fully age-structured groups). Some of the smaller groups (e.g. microflora primary producers) and the inanimate pools can exist in both the sediments and water column (@tbl-state-variables).

In the Atlantis code the water column, epibenthic, sediment, ice and land distributions are referred to as "habitatType". However, remember that they are not the same as the ecological epibenthic habitats modelled in Atlantis (e.g. seagrass, corals, sponges etc.).

| **Group** | **State variables tracked** | **[GroupType]{style="color: orange;"} in CSV file or *initial_conditions.nc*** |
|:----------|:-----------------------------|:------------------------------------------------------|
| **Biomass pools** | | |
| pelagic **bacteria** | N in water column | PL_BACT |
| sediment **bacteria** | N in sediments | SED_BACT |
| **Age-structured biomass pools** | | |
| *These groups can be age structured if [NumCohorts]{style="color: orange;"} set > 1* | | |
| non epibenthic **primary producers** | N in water column<br>N in sediments<br>\*Si in water column<br>\*Si in sediments<br>NOTE: Age-structure not recommended | SM_PHY<br>LG_PHY<br>MICROPHTYBENTHOS<br>DINOFLAG |
| epibenthic **primary producers** | N in epibenthic layer for each age group defined by [NumCohorts]{style="color: orange;"} parameter. If age-structure is selected for SEAGRASS it is not really age structure, but different parts of the plant — with "age 0" assumed to be the pool representing leaves, "age 1" the roots, and "age 2" the epiphytes on the leaves, see details [here](https://atlantis-ecosystem-model.github.io/atlantis-wiki/posts/new-seagrass-modelling-option.html) | PHYTOBEN<br>SEAGRASS |
| infaunal **invertebrates** | N in sediments for each age group defined by the [NumCohorts]{style="color: orange;"} parameter.<br>NOTE: Not typically age-structured | SM_INF<br>LG_INF |
| epibenthic **invertebrates** | N in epibenthic layer for each age group defined by the [NumCohorts]{style="color: orange;"} parameter | SED_EP_FF<br>SED_EP_OTHER<br>MOB_EP_OTHER<br>CORAL<br>SPONGE |
| water column **invertebrates** | N in water column for each age group defined by the [NumCohorts]{style="color: orange;"} parameter | SM_ZOO<br>MED_ZOO<br>LG_ZOO |
| land **plants** | N on land for each age group defined by the [NumCohorts]{style="color: orange;"} parameter | MARSH<br>MANGROVE |
| large invertebrates | N in water column for each age group defined by [NumCohorts]{style="color: orange;"} parameter | CEP<br>PWN |
| **Age-structured groups** | | |
| vertebrates | RN in water column<br>SN in water column<br>Num in water column<br>for each cohort defined in [NumCohorts]{style="color: orange;"} parameter | FISH<br>SHARK<br>MAMMAL<br>BIRD<br>REPTILE |
| size/age structured invertebrates of particular interest | RN in water column<br>SN in water column<br>Num in water column<br>for each cohort defined in [NumCohorts]{style="color: orange;"} parameter | FISH_INVERT |
| **Inanimate pools** | | |
| Ammonia | NH3 in water column<br>NH3 in sediments | NH |
| Nitrate | NO3 in water column<br>NO3 in sediments | NO |
| Oxygen | O2 in water column<br>O2 in sediments | O2 |
| Dissolved organic nitrogen | DON in water column<br>DON in sediments | DON |
| Dissolved silica | Si in water column | Si |
| Detrital silica | DSi in water column | DSi |
| Labile detritus | N in water column<br>N in sediments | LAB_DET |
| Refractory detritus | N in water column<br>N in sediments | REF_DET |
| Carrion (only dynamically tracked if fisheries are active) | N in water column<br>N in sediments | CARRION |
| Sediment (only if [flagIsEstuary]{style="color: orange;"}=1) | SED in water column | SED |

: State variables tracked in the main Atlantis model (no ice or land included). \* indicates optional Si tracking in primary producers that are limited by Si. Primary producer Si limitation is set in *functional_groups.csv* file parameter [IsSiliconDep]{style="color: orange;"} (see @tbl-functional-group-params). In models that include C and P, both C and P are tracked like N (so the number of variables tracked is three times larger). {#tbl-state-variables tbl-colwidths=[30,45,25]}



### Timestep of the model

The timestep at which most processes are repeated is typically an *adaptive* daily (24h) or diurnal (12h) timestep, though tidal models with shorter timesteps (3h or 6h) also exist. This timestep is specified as [dt]{style="color: orange;"} in the *run.prm* file. Reproduction, recruitment and migration occur less frequently, typically once per year.

The *adaptive timestep* means that for most of the groups the processes are repeated once per timestep, but for small organisms, such as bacteria and phytoplankton the timestep is reduced to ensure that fluxes into and out of the component with the fastest turnover rates remain stable and numerical artifacts are not introduced into the mathematical solution scheme. The length of the adaptive timestep for such groups is determined to ensure that the relative change (flux) in any variable does not exceed a pre-specified proportion of the standing stock — this tolerance is set in the *biology.prm* file. The adaptive timestep changes through time, depending on the standing stock of these groups and the temperature, nutrient availability and other factors that affect the turnover rates in these "fast" variables.

### Biological processes modelled

The modelled biological processes include primary production, bacterial processes, feeding, assimilation, waste production, explicit respiration (optional and not used in most models), growth, movement and migration, non-predation mortality, maturation, reproduction and recruitment. In biomass pools all processes are modelled through biomass (nitrogen) turnover. In age-structured groups, the state variables are numbers-at-age and weight-at-age (tracked as reserve and structural nitrogen) which can be converted to biomass.

## Defining functional groups 

The functional group input file sets all the biological groups in the model. It can be set in CSV or XML format (see examples [here](https://atlantis-ecosystem-model.github.io/atlantis-wiki/functional-group-definition-file.html)). The number of groups is entirely flexible, but each model must include three obligatory detritus groups: carrion (CARRION), labile detritus (LAB_DET) and refractory detritus (REF_DET).

::: {.callout-note}
The *functional_groups.csv* file defines the biological groups used in the model and some of their key characteristics. These characteristics are used throughout the code to apply different appropriate routines for the group. The number of groups in the *functional_groups.csv* file must match the number given in the [K_num_tot_sp]{style="color: orange;"} parameter in the *run.prm* file. The detritus groups must be defined as the last three groups in the file.
:::

Currently each group must have the following parameters (characteristics). For new updates, check the Atlantis wiki [functional group page](https://atlantis-ecosystem-model.github.io/atlantis-wiki/functional-group-definition-file.html)

| **Parameter name** | **Description** |
|:-------------------|:----------------|
| [GroupCode]{style="color: orange;"} | **2 or 3 letter code** of upper case letters used to identify each functional group. Atlantis will display an error message and quit if the group codes are not the correct format. This code is very important and applied to all functional group specific parameters |
| [Index]{style="color: orange;"} | An index of the group. Atlantis doesn't actually read this in but it is helpful for modellers to see as it defines the order of read-in for species vectors and the group ID number if you are trying to activate some of the debug/calibration fprintf statements using [whichcheck]{style="color: orange;"} in the *run.prm* file. The index must start from 0, as this is how the C programming language counts |
| [IsTurnedOn]{style="color: orange;"} | A boolean value (either 0 (false) or 1 (true)) to indicate if the group is active in the current model run. If the group is not active it will be excluded from the model.<br><br>This option allows the user to exclude some groups from the model without having to setup new initial conditions and parameter files. |
| [Name]{style="color: orange;"} | Name of a group. This must match the tracer names in the *initial_conditions.nc* file as it is used to find the tracers in the *initial_conditions.nc* input file. |
| [LongName]{style="color: orange;"} | The long name written to the NetCDF output files. This name can be a few words long and ideally should be informative. This is especially important when sharing the model with others. |
| [NumCohorts]{style="color: orange;"} | The number of cohorts in a functional group. If the value is > 1 the groups is assumed to be age-structured (either an age-structured biomass pool or age-structured group).<br><br>In the earlier Atlantis versions age structured groups all had to have 10 cohorts. This is now relaxed and there is no upper limit on the number of age-groups to model (but remember, the more age groups the slower the model will run). |
| [NumGeneTypes]{style="color: orange;"} | Number of discrete phenotypes in each age group. This option is used when simulating evolution or multiple size-at-age representations and should only be set to >1 if [flag_do_evolution]{style="color: orange;"} is set to 1 in *biology.prm* file. If more than one phenotype is present, initial conditions will have to be set up for each phenotype. |
| [NumStages]{style="color: orange;"} | This parameter describes the number of separate stages in a functional group, which are set to 1 or 2 if juvenile and adult stages have separate parameters for distribution, mortality, migration, feeding and others. In principle, more than 2 stages are possible, although this has not been tested. Typically all age-structured groups have 2 stages, but age-structured biomass pools can also have separate parameters for juvenile and adult stages and thus have 2 stages. |
| [NumSpawns]{style="color: orange;"} | Number of spawns in the year. Typically one per year, but more than one is possible (especially for ages structured biomass pool groups). The timing of spawn is given in [Time_Spawn_XXX]{style="color: orange;"} parameter in *biology.prm* file (if [NumSpawns]{style="color: orange;"} is 1 it expects a single value, otherwise it expects a vector of length [NumSpawns]{style="color: orange;"}). |
| [NumAgeClassSize]{style="color: orange;"} | Number of calendar years in one age group. This can be set to be anything between a few months to many years and allows simulation of different longevity organisms without having to setup too many age groups (which reduces simulation speed). Note, all individuals in an age group are considered identical (unless different phenotypes are set in [NumGeneTypes]{style="color: orange;"}, in which case all individuals in one phenotype of one age group are identical). However, the proportion of an age group per annual cohort is tracked so that recruitment variation is represented through time and not homogenized away (@sec-age-at-recruit). |
| [NumStocks]{style="color: orange;"} | This sets the number of geographically distinct stocks for age-structured groups and age-structured biomass pools. The stocks must occupy different boxes or layers, i.e. they do not spatially overlap.<br><br>Some biological parameters, like vulnerability to prey can be set as stock specific, which allows for better tuning. It has been applied to some groups that are known to include ecologically distinct stocks in different geographic areas. If [NumStocks]{style="color: orange;"} >1 then the corresponding number of stock specific parameters will be required in the *biology.prm* input file |
| [VerticallyMigrates]{style="color: orange;"} | If true then the group can move vertically through the water column. This should be set to 1 except for debugging purposes. If this is set to 0, no vertical movement will happen even if it is specified in the *biology.prm* file and the vertical distribution of individuals in the *initial_conditions.nc* file will be retained throughout the simulation. |
| [HorizontallyMigrates]{style="color: orange;"} | If true then the group can move horizontally throughout the model as well as migrate out of the model. No migration will happen if this is set to 0. Biomass pool groups which are marked as passive in the *initial_conditions.nc* will still be advected even if [HorizontallyMigrates]{style="color: orange;"} is set to 0. |
| [NumMigrations]{style="color: orange;"} | The number of migrations per calendar year |
| [MultiYrMigrations]{style="color: orange;"} | Whether any of the migrations are multi-year (1) or simply annual (0). While this column is always required in the groups definition file the associated code will not function unless [flag_multiyr_migs]{style="color: orange;"} is also set to 1 in the *run.prm* file |
| [ExternalReproduction]{style="color: orange;"} | This is whether the group reproduces outside the model (i.e. the value for [Time_Spawn_XXX]{style="color: orange;"} parameter in *biology.prm* file is set during a day of the year when the species should be outside the model) |
| [RecruitType]{style="color: orange;"} | This is where you set the recruitment type:<br><br>0 = independent distribution (use recruit_hdistrib)<br>1 = at parental locations<br>2 = external (into Migration Array)<br>3 = using a forced larval dispersal matrix<br>4 = external reproducer who has parental care |
| [IsFished]{style="color: orange;"} | If set to 1 the group can be fished (targeted) by commercial or recreational fisheries and the catch will be reported in the output files, and is analysed in the assessment model. Note that if set to 0, dynamic fishing will still occur if parameters are given in the *harvest.prm* file. |
| [IsImpacted]{style="color: orange;"} | If true then the group can be impacted by fishing, bycatch or incidental fishing related mortality (e.g. destruction of living habitats). This parameter differentiates between targeted and accidental interactions; it is not reported in the landings. This means there must be values in the harvest files for this group. Note the group can be impacted by bycatch/incidental mortality even if no explicit targeted fishing is setup. This means the bycatch/incidental mortality parameters should be assessed carefully in the *harvest.prm* file.<br><br>If both this value and [IsFished]{style="color: orange;"} are set to 0 then all fisheries related impacts on the group are disabled. |
| [isTAC]{style="color: orange;"} | If true, the group will be under total allowable catch (TAC) management. It will activate specific TAC related code in the Harvest submodel. |
| [GroupType]{style="color: orange;"} | The type of species. This is one of the most important parameters, as it tells Atlantis what kind of organism the functional group is representing and what kind of processes should be applied to it. Six group types are allowed for age-structured groups. A lot more group types are available to define invertebrate biomass pool types and these group types are used to dictate the adaptive timestep for simulating processes, and all of them have some specialized ecological routines applied (see some details about their characteristics [here](https://atlantis-ecosystem-model.github.io/atlantis-wiki/atlantisgrouptypes.html)).<br><br>The main Atlantis model groups include:<br><br>**AGE STRUCTURED GROUPS**<br><br>1) Standard fin-fish or generic vertebrate FISH<br>2) Size/age-structured invertebrate FISH_INVERT<br>3) Chondrichthyans SHARK<br>4) Birds BIRD<br>5) Marine mammals (potentially terrestrial mammals in the future) MAMMAL<br>6) Reptiles (can be present in the water and on land) REPTILE.<br><br>**BIOMASS POOL GROUPS**<br><br>**Phytoplankton**<br><br>7) Small Phytoplankton SM_PHY<br>8) Large Phytoplankton LG_PHY (used in combination with [IsSiliconDep]{style="color: orange;"} to define diatoms)<br>9) Trichodesmium and Cyanobacteria TRICHO (N fixers)<br><br>**Other primary producers**<br><br>10) Microphytobenthos MICROPHTYBENTHOS<br>11) Dinoflagellates DINOFLAG<br>12) Phytoben PHYTOBEN (typically used to represent macroalgae)<br>13) Seagrass SEAGRASS<br>14) Turf TURF<br><br>**Zooplankton**<br><br>15) Small Zooplankton SM_ZOO<br>16) Medium Zooplankton MED_ZOO<br>17) Large Zooplankton LG_ZOO<br>18) Jellyfish JELLIES (in the past represented as LG_ZOO)<br><br>**Large pelagic invertebrates**<br><br>19) Cephalopod CEP<br>20) Prawns PWN<br><br>**Infauna**<br><br>21) Small Infauna SM_INF<br>22) Large Infauna LG_INF<br><br>**Epibenthic organisms**<br><br>23) Sediment epibenthic filter feeders SED_EP_FF (often used for bivalves, sponges)<br>24) Benthic grazers SED_EP_OTHER<br>25) Mobile epibenthos MOB_EP_OTHER (often used for crabs, lobster, octopus)<br>26) Corals CORAL<br>27) Sponges SPONGE<br><br>**Bacteria**<br><br>28) Pelagic Bacteria PL_BACT<br>29) Sediment Bacteria SED_BACT<br><br>**Obligatory detritus groups**<br><br>30) Carrion CARRION<br>31) Labile detritus LAB_DET<br>32) Refractory detritus REF_DET<br>33) Additional ice and land based groups are also available.<br><br>**Ice dwelling**<br><br>34) ICE_BACT<br>35) ICE_MIXOTROPHS<br>36) ICE_DIATOMS<br>37) ICE_ZOOBIOTA<br><br>**Land dwelling** (vegetation only for now)<br><br>38) MARSH<br>39) MANGROVE |
| [IsPredator]{style="color: orange;"} | If true then the group is assumed to eat other groups by the assessment code (for the purposes of defining network indices etc), it does not affect the ecological model. |
| [IsCover]{style="color: orange;"} | If true the group is classified as a habitat. This means that the group becomes a unique habitat type, that can be used by other groups in the model for shelter etc, in addition to the general four geological habitat types included by default (**reef, flat, soft, canyon**).<br><br>For example, if [IsCover]{style="color: orange;"} is set to 1 for three functional groups (e.g. BFS, BFF, and MA), the model has a total of seven habitat types. In this case the habitat dependency parameter [habitat_XXX]{style="color: orange;"} in the *biology.prm* file must have 7 values for each functional group. The living habitats are always the first entries and the geological classes always the last 4 entries. So in this example, the first three entries will refer to the [IsCover]{style="color: orange;"} groups in the order they are listed in the *functional_groups.csv* file and the last four entries will refer to reef, flat, soft, canyon habitats. |
| [IsSiliconDep]{style="color: orange;"} | If true, the group is assumed to be Si limited and its energy flows are tracked both through nitrogen and silicon. All Si limited groups must have separate Si tracers set in the *initial_conditions.nc*, in addition to the usual Nitrogen tracers. At present most models have this set to true for Diatoms and MicroPhytobenthos. |
| [IsAssessed]{style="color: orange;"} | If true then this group will be assessed in the Assessment submodel. This submodel will generate a number of assessment indices. |
| [IsCatchGrazer]{style="color: orange;"} | If true, the group grazes on catch, for instance pinnipeds that eat fish from nets. If set to 1 for a functional group XXX, then availability of catch of each functional group should be given for this group in the [pFCXXX]{style="color: orange;"} parameter in the *biology.prm* file. The pFC parameters are not required for groups that are not catch grazers. |
| [OverWinters]{style="color: orange;"} | If true, this group will go into hiatus over winter. The overwintering can be triggered and ended by time of the year or temperature. This is set using [overwinterStartTofY_XXX]{style="color: orange;"}, [overwinterEndTofY_XXX]{style="color: orange;"}, [overwinterStartTemp_XXX]{style="color: orange;"}, [overwinterEndTemp_XXX]{style="color: orange;"} parameters in the *biology.prm* file. These parameters only have to be set for overwintering groups. |
| [isCultured]{style="color: orange;"} | This identifies aquaculture groups, and applies aquaculture processes to them. Parameters required for aquaculture groups are described [here](https://atlantis-ecosystem-model.github.io/atlantis-wiki/posts/aquaculture.html). |
| [isHabDepend]{style="color: orange;"} | Identifies groups that are habitat dependent. Note, this value takes precedence over habitat preference parameters in the *biology.prm* file. If [isHabDepend]{style="color: orange;"} is set to 0 then the group is not affected by habitats, even if appropriate parameters are given in the *biology.prm*. |
| [numMoveEntries]{style="color: orange;"} | The number of movement time periods you would like the group to have. Historically this has been fixed at 4 to allow for seasonal movement, but currently any number of moves is allowed. See [further details on parameters in *biology.prm*](https://atlantis-ecosystem-model.github.io/atlantis-wiki/finding-all-the-options-for-the-flags.html).|
| [isBioEroder]{style="color: orange;"} | Whether the group bioerodes corals (e.g. sponges). This allows for boring sponges and bioeroder activities in reef models including corals and sponges |
| [isSupplemented]{style="color: orange;"} | Whether the group feeds on material from outside the model. If this is set to 1, the group will be assumed to be eating insects or pellets or something from outside the model domain. The proportion of their diet gained in this way (per box) must be set using the [Supp_XXX]{style="color: orange;"} in the *biology.prm* file. |
| [isExternal]{style="color: orange;"} | Flag to indicate whether the group uses the external population model option (instead of simply holding individuals in hiatus when they have migrated out of the model). |
| [isLandActive]{style="color: orange;"} | Marks the group as able to be on land (for models with land and sea). Only required if [flagAllowLand]{style="color: orange;"} is set to 1 in the *run.prm* file. |
| [isLightEffected]{style="color: orange;"} | Marks the group as susceptible to light pollution. Only required if [flag_pollutant_impacts]{style="color: orange;"} is set to 1 in the *run.prm* file. |
| [isNoiseEffected]{style="color: orange;"} | Marks the group as susceptible to noise pollution. Only required if [flag_pollutant_impacts]{style="color: orange;"} is set to 1 in the *run.prm* file. |

: Parameters in the *functional_groups.csv* file. {#tbl-functional-group-params tbl-colwidths=[25,75]}


::: {.callout-note}
**What is the role of detritus in an ecosystem model? An excerpt from Murray and Parslow (1997) PPBIM report:**

"The detrital pool acts as a store of fixed nutrient, which introduces a delay into nutrient recycling. Particulate detritus sinks and thereby transports nutrients out of the surface layer into deep water or to the sediment. Dissolved organic matter (DOM) does not sink, and very large pools of refractory DOM are found in the open ocean and in coastal waters. Horizontal transport of particulate detritus and DOM from regions of high production to more oligotrophic areas can also be important"

"Three forms of non-living organic matter are included in the model: labile particulate detritus, refractory particulate detritus and dissolved organic matter [NOTE — these same pools, plus Carrion, are included in Atlantis, which is based on the PPBIM]. These are represented by the symbols DL, DR and DON respectively. The particulate detrital pool [in nature] contains a wide variety of particles, with diverse sources, ages, sizes and chemical composition. The model includes two functional components: fresh labile detritus breaking down on time scales of a few days, and semi-refractory detritus turning over on time scales of a year. This allows the model to treat perturbations to the nutrient cycle on time scales of days to years."

"[In nature] The pool of dissolved organic matter also contains a variety of compounds with diverse turnover rates. In oceanic waters there is a large pool of highly refractory DOM, whose average age has been estimated to be as much as 3400 years (Williams 1975). The bulk of this material is essentially irrelevant for the cycling of nutrients on the time scales of [model] interest. However the DOM pool also includes much more labile components. Highly labile sugars and amino acids released through cell lysis or messy feeding may be consumed by bacteria or break down on time scales of hours (Fuhrman 1987) to days (Holibaugh and Azam 1983). This material is not modelled explicitly, but is treated as though it was remineralised immediately to form dissolved inorganic nutrient. The model includes a single DOM pool with an assumed turnover time of the order of a hundred days. ... Because it turns over on time scales, which are long compared with both phytoplankton uptake of inorganic N, and transport within the Bay, it plays a role in reducing N sequestration in coastal waters."
:::

## Defining the [GroupType]{style="color: orange;"} correctly 

The definition of a group is very important as it will determine the ecological routines and the adaptive timestep applied for the group (see timestep description in chapter 6.1). Routines called for different group types are listed in @tbl-atlantis-routines. The routines are further modified depending on whether consumers live in the water column or sediment.

| **Routine name in Atlantis code** | **[GroupType]{style="color: orange;"} for which the routine is applied** |
|:-----------------------------------|:------------------------------------------------|
| *Dinoflag_Process()* | DINOFLAG<br>ICE_MIXOTROPHS |
| *Phytoplankton_Process()* | LG_PHY<br>SM_PHY<br>PHYTOBEN<br>SEAGRASS<br>MICROPHTYBENTHOS<br>TURF<br>ICE_DIATOMS |
| *Invert_Consumers_Process()* | **SM_INF**<br>**LG_INF**<br>SM_ZOO<br>MED_ZOO<br>LG_ZOO<br>CEP<br>PWN<br>ICE_ZOOBIOTA |
| *Epibenthic_Invert_Process()* | **SED_EP_FF**<br>**MOB_EP_OTHER** |
| *Sediment_Epi_Other_Process()* | **SED_EP_OTHER** |
| *Coral_Process()* | CORAL<br>SPONGE |
| *Pelagic_Bacteria_Process()* | PL_BACT |
| *Ice_Bacteria_Process()* | ICE_BACT |
| *Sediment_Bacteria_Process()* | SED_BACT |
| *Labile_Detritus_Process()* | LAB_DET |
| *Refractory_Detritus_Process()* | REF_DET |
| *Carrion_Process()* | CARRION |

: Routines called for different non-vertebrate GroupTypes in Atlantis code. The *Call_Group_Process_Function()* routine in **atecology.c** determines the specific routine used from the **atGroupProcess.c** file for non-vertebrate groups. Note that the greatest diversity of routines are called for different benthic invertebrate types (for clarity benthic invertebrates are shown in **bold**). {#tbl-atlantis-routines tbl-colwidths=[40,60]}

## Modifying functional groups in parameterised models 

Details on how to add a new functional group into an existing model are given on the wiki [here](https://atlantis-ecosystem-model.github.io/atlantis-wiki/adding-a-new-group.html). This will require a significant effort and reparameterisation of the model.

Alternatively, if changes to functional groups are needed, it might be easier to use an existing group and change it into something new. You may not want to change the three letter code, as that would involve changing all the parameter names for the group.