# Run Parameters {#sec-run-parameters}

The *run.prm* provides all the key information required to control the model run, load optional submodels and also parameters controlling the debugging and detailed output. The table below lists the main parameters used in the *run.prm*, but please remember to follow the news on the Atlantis wiki as new parameters are sometimes added.

::: {#tbl-run-parameters}

### General parameters controlling the run

| **Parameter** | **Meaning** |
|:--------------|:------------|
| [title]{style="color: orange;"} | Title of the run. Ideally this should be an informative title (e.g. SE Tasmania model with constant forced fishing and base level fishing pressure on FMM increased 2000 fold) as it will be written at the start of the *log.txt* file and into the *output.nc* file and will be displayed on the top of plots in visualization tools such as OLIVE or DIVE |
| [dt]{style="color: orange;"} | Timestep of the model. The timestep is typically given in hours (e.g. "12 hour"), however Atlantis reads the units together with the numerical value so other units "minute" or "day" may also be used. Typically the timestep is set to 12 or 24 hours, but it can be set to other intervals as well. It is not typically recommended to make it >24h and one should think carefully whether shorter than 12h is really needed, as the model will run slower. Some coastal, very dynamic, areas have 6h or even 3h timesteps, but that will require high resolution hydrodynamic forcing data. |
| [tstop]{style="color: orange;"} | Day on which the model run will end. If you want to run the model for 10 years, set this to 3651 (technically 3650, however given most output is done annually it is best to add an extra day to make sure the final output is printed before the model stops). |
| [tburnday]{style="color: orange;"} | Number of days that define the burn-in period. At the end of this period the "virgin" state of the model is stored. This means that every comparison of species biomass to the original or "virgin" state will use values stored at the end of the burn-in period and not those set in the initial conditions. This is useful for models that have unstable dynamics at the start of the model run. |

: General parameters controlling the run. {#tbl-run-parameters-general tbl-colwidths=[25,75]}

### Output files and reporting

| **Parameter** | **Meaning** |
|:--------------|:------------|
| [toutstart]{style="color: orange;"} | Day on which to start writing the output. This is normally set to 0, but can be set to a larger value for long runs if there is a need to save memory and there is no interest in the burn-in period dynamics. |
| [toutinc]{style="color: orange;"} | Periodicity in days for the Ecology submodel snapshot output to the NC files. In longer runs, this is often set to monthly (30) or yearly (365) so file sizes do not become very large. In poorly behaved runs (that are crashing), or ones with extreme events which condition subsequent behaviour, fine scale output (e.g. at the same level as the timestep) may be required. However, remember that a lot of output is written at each reporting period, so make sure you set reasonable values for long well-behaved runs (quarterly or even yearly).<br><br>Note that in Atlantis all years are 365 days long. If monthly output is required and it is set to 30 days then after one year the output would be shifting by 5 days every year. |
| [toutfinc]{style="color: orange;"} | Periodicity of the cumulative output from the Harvest submodel (catches, quotas, discards, etc) to the NC files (*CATCH.nc*, *TOTCATCH.nc*). These values are the sum of all effort, catch (etc) since the last output dump. Unlike the ecology output, they are not snapshot values. |
| [tsumout]{style="color: orange;"} | Periodicity of the output to the TXT files. |
| [flagannual_Mest]{style="color: orange;"} | If 1, estimates of mortality per predator are written out annually, otherwise they are written at the [tsumout]{style="color: orange;"} frequency |
| [fishout]{style="color: orange;"} | If 1, it switches on the fisheries output (it is recommended that this is on if you have fisheries in your model, but is unnecessary if it is an ecology model only). |
| [flagreusefile]{style="color: orange;"} | Whether to replace or append outputs to the existing files, when starting a new run. If it is set to 0 Atlantis will quit with a message that a file with such name already exists. If it is set to 1 results will be appended to the existing file, if set to 2 it will overwrite (replace) the existing file without warning.<br><br>**NOTE:** This is old code. If you really want it to append please run a test first to see if it worked. If not, let the developers know, as it likely needs updating. Setting [flagreusefile]{style="color: orange;"} to 0 or 2 is recommended. |
| [flag_age_output]{style="color: orange;"} | If set to 1, an additional output file *agebiomindex.txt* will be created and the total biomass output will be given for each cohort. This can be a very useful output file, because without it you will need to run a specially written script over the *output.nc* file to determine the biomass per age group per functional group. |

: Output files and reporting. {#tbl-run-parameters-output tbl-colwidths=[25,75]}

### Parameters loading different submodels or options

| **Parameter** | **Meaning** |
|:--------------|:------------|
| [flagecon_on]{style="color: orange;"} | If 0 the Economics submodel is not loaded |
| [flag_fisheries_on]{style="color: orange;"} | If 0 the Harvest submodel is not loaded |
| [flag_skip_biol]{style="color: orange;"} | If 1 the Ecology submodel is not loaded — only for debugging! |
| [flag_skip_phys]{style="color: orange;"} | If 1 the Physics submodel is not loaded. This will actually produce an error message and Atlantis will quit. **So this value should NEVER be set to 1.** |
| [fishmove]{style="color: orange;"} | If 0 all age structured group movements (vertical and horizontal) are turned off |
| [external_populations]{style="color: orange;"} | Flag indicating whether an age structured population dynamics model is used to track growth and mortality while an age-structured group is outside the model domain (1) or whether a simple growth and mortality correction is applied to migrators on their return to the system (0) |

: Parameters loading different submodels or options. {#tbl-run-parameters-submodels tbl-colwidths=[25,75]}

### Parameters controlling detailed outputs and diagnostic reporting

*The outputs are written into the log.txt file for model tuning and debugging purposes.*

| **Parameter** | **Meaning** |
|:--------------|:------------|
| [debug_it]{style="color: orange;"} | If 1 — give detailed outputs of all processes for a selected box and time period into the *log.txt* file |
| [checkbox]{style="color: orange;"} | Box number for which to give detailed outputs into *log.txt* file |
| [checkstart]{style="color: orange;"} | Day on which the detailed output in the *log.txt* file for the box above should start |
| [checkstop]{style="color: orange;"} | Day on which the detailed output in the *log.txt* file for the box above should end<br><br>**Note!** Detailed output will likely produce a huge amount of data, so make sure the time period of detailed reporting is not too long or the run is short |
| [debug]{style="color: orange;"} | Controls which topic area or code path produces detailed debug output. See @sec-debug-values for the full list of values. |
| [fishtest]{style="color: orange;"} | If 1, count up total population of age structured groups after each main subroutine |
| [flaggape]{style="color: orange;"} | Periodically list prey vs gape statistics in *log.txt* |
| [flagchecksize]{style="color: orange;"} | Periodically list relative size in *log.txt*. This is useful during model calibration for seeing the current size versus size given in the initial conditions. |
| [flagagecheck]{style="color: orange;"} | Periodically list age structure per cohort in *log.txt* |
| [flagdietcheck]{style="color: orange;"} | Writes detailed diet output per box and layer to *DetailedDietCheck.txt*<br><br>If set to 1 then it is total consumption, if set to 2 then it returns proportions |
| [checkNH]{style="color: orange;"} | Give detailed logged output for NH fluxes in the box selected with [checkbox]{style="color: orange;"}. Useful for understanding what groups may be at fault if you get an "unstable variable" crashing the model before completion of the run. |
| [checkDL]{style="color: orange;"} | Give detailed logged output for DL fluxes in [checkbox]{style="color: orange;"}. Useful for understanding what groups may be at fault if you get an "unstable variable" crashing the model before completion of the run. |
| [checkDR]{style="color: orange;"} | Give detailed logged output for DR fluxes in [checkbox]{style="color: orange;"}. Useful for understanding what groups may be at fault if you get an "unstable variable" crashing the model before completion of the run. |
| [checkbiom]{style="color: orange;"} | Give detailed logged output for biomasses of [which_check]{style="color: orange;"} group in the [checkbox]{style="color: orange;"} (see above) |
| [which_fleet]{style="color: orange;"} | ID number of fleet to track (if you don't want to track anything set this to a value greater than the number of fisheries in your model). The ID is the same as in the *fisheries.csv* file |
| [which_check]{style="color: orange;"} | ID number of group to track (if you don't want to track anything set this to a value greater than the number of functional groups in your model). The ID is the same as in the *functional_groups.csv* file |
| [habitat_check]{style="color: orange;"} | Which distribution type (0 = water column, 1 = sediment, 2 = epibenthic, 3 = land, 4 = ice) to report for the group marked with [which_check]{style="color: orange;"}. Some groups are only tracked in one distribution type, others are tracked in both water column and sediments. |
| [move_check]{style="color: orange;"} | ID number of group for which movements should be tracked |

: Parameters controlling detailed outputs for a specific box and diagnostic reporting. {#tbl-run-parameters-debug tbl-colwidths=[25,75]}

### Key parameters determining the model runs and inputs

| **Parameter** | **Meaning** |
|:--------------|:------------|
| [flaghemisphere]{style="color: orange;"} | 0 = southern, 1 = northern hemisphere. This flag is important in calculating winds and circulation (affects coriolis and seasons). |
| [flagAllowLand]{style="color: orange;"} | Set to 1 if the model includes dynamic land components (this requires a large number of additional inputs). If set to 0 any land boxes are treated as boundary boxes and are not executed. |
| [flagIsEstuary]{style="color: orange;"} | Flag to indicate if the model is an estuary. If true a SED sediment tracer is required in the initial conditions input file and tidal emptying of shallow boxes is allowed (with fish moved to the nearest water channel). |
| [flagIsPolar]{style="color: orange;"} | Flag to indicate whether the model is in polar regions and so will have 24 hours of night/daylight seasonally |
| [flag_use_deltaH]{style="color: orange;"} | Flag to indicate that when using pH tracking and parameter corrections use ∆ [H+] rather than pH *per se*. |
| [trackAtomicRatio]{style="color: orange;"} | If set to 1, then not only N, but also P and C are tracked. This will require many additional tracers in the input files. |
| [track_rugosity_arag]{style="color: orange;"} | If set to 1, rugosity and aragonite saturation will be tracked and additional parameters required. Important for modelling corals and sponges. |
| [track_pH]{style="color: orange;"} | If set to 1, pH values will be tracked — important for ocean acidification simulations. |
| [track_contaminants]{style="color: orange;"} | If set to 1, contaminants will be tracked. This will require information on the number and name of the contaminants to be tracked, as well as additional tracers and initial conditions (so as to allow for the tracking of contaminants through each of the functional groups in the model). |

: Key parameters determining the model runs and inputs. {#tbl-run-parameters-keyinputs tbl-colwidths=[25,75]}

### Other parameters

| **Parameter** | **Meaning** |
|:--------------|:------------|
| [mirror_invalid]{style="color: orange;"} | If this flag is set to 1 and the hydrodynamics model attempts to send water from one cell into an invalid cell (e.g. a layer in a box that does not exist) the water flow will instead be sent into the layer closest to the intended destination layer. This option was needed because historically some hydrodynamic models tried to send water into layers below what Atlantis was modelling, so water had to be redirected to the extant bottom layer instead. Set this flag to 0 if your hydrodynamic forcing is working well or you want Atlantis to quit with a warning that something is wrong with the hydrodynamic forcing files. |
| [flag_replicated_old]{style="color: orange;"} | This flag is used to maintain legacy code options. While we fix true bugs sometimes we also update the code to better represent a process where we had made a rough first attempt that can now be done in a better way. However, such changes can change model dynamics and so for legacy models we need to keep the legacy options. When set to 1, the new code changes are not applied and the old results can be reproduced. However, for all new models it is recommended that this flag be set to 0, as the new code is more rigorous and defensible. |
| [flag_replicated_old_PPmort]{style="color: orange;"} | Flag used to maintain old plankton mortality assumptions (from very early code versions that persisted as a potential bug into newer models). Turning it on zeroes out phytoplankton mortality and only allows for lysis in phytoplankton. However, for all new models it is recommended that this flag be set to 0 so parameter application is transparent and contaminants are transferred appropriately.<br><br>If you are transitioning an old model and want to have this flag turned off but maintain your old model as close as possible, keep your lysis values as is and zero out mL. |
| [flag_replicate_old_calendar]{style="color: orange;"} | This flag specifically allows for legacy models and the influence of environment on the distribution of recruits to be replicated in the newer code. It is recommended that all new models have this set to 0. |
| [flag_old_embryo_init]{style="color: orange;"} | This flag is to allow legacy models to have the same starting conditions under the new code as they did in older versions. In the past, rather than use the stock-recruit relationship for a species to dictate the larvae already in the water column at the start of the model run, a simpler linear relationship with spawning stock was used. This has now been replaced by the use of the stock-recruit relationship (for improved consistency). All new models should set this parameter to 0, but legacy models trying to reproduce past model runs should set this value to 1. |
| [check_dups]{style="color: orange;"} | If set to 1, Atlantis will check for duplicated parameters in the parameter files before starting the run. This can be used to ensure that the same parameter is not entered twice with different values. However, it takes a LONG time to execute (especially for big models). If it is set to 1 the model run will not start for quite a while until all possible duplicates are checked. If you are concerned about duplicate entries, go through the file once with this until all duplicates are found and then turn it off. |
| [flagscaleinit]{style="color: orange;"} | If set to 1 this will cause the vector [init_scalar]{style="color: orange;"} to be read in. This vector contains one value per group listed in the *functional_groups.csv* file. These values are used to modify (scale) the initial conditions without requiring modification to the NC — for the vertebrates the number per age class is scaled and for biomass pools the biomass per cell and layer is scaled (for those groups in the water column, sediment layers and the epibenthos). |
| [flag_sanity_check]{style="color: orange;"} | Set this to 1 to make sure that species with a gestation or recruitment period that is about the same length as the time between reproduction (spawning) events do not get cascading population growth (where recruits from one event accidentally also contribute to the next event). To replicate old code versions set this value to 0. |
| [flagpassivetracer]{style="color: orange;"} | Set to 1 if you want to do particle tracking to validate physical forcing. This will require adding the SED_i variable to the *initial_conditions.nc* file. |
| [flagenviro_warn]{style="color: orange;"} | Set to 1 if you want warnings about when environmental conditions constrain spawning or movement in a cell. |
: Other parameters. {#tbl-run-parameters-other tbl-colwidths=[25,75]}

## Debug parameter values {#sec-debug-values}

The [debug]{style="color: orange;"} parameter triggers `fprintf` lines in the code and prints information to the *log.txt* file. Setting it to 0 turns off detailed outputs. Other values focus on different processes:

| Value | Topic |
|:-----:|:------|
| 1 | Fisheries catch fprintf |
| 2 | Discards |
| 3 | Forced fish catches |
| 4 | Assessment model processes |
| 5 | Spatial management |
| 6 | Basic effort options |
| 7 | Economically driven effort allocation model |
| 8 | Economic calculations |
| 9 | Quota setting and handling |
| 10 | Aging in age structured groups |
| 11 | Recruitment in age structured groups |
| 12 | Spawning in age structured groups |
| 13 | Migration in/out of model domain |
| 14 | Movement within the model domain |
| 15 | Stock-based allocations within a functional group |
| 16 | Basic overall biomass calculations |
| 17 | Feeding |
| 18 | All ecological processes |
| 20 | Print biology process function parameters |
| 21 | Print prey function parameter |
| 22 | Debug clam-Atlantis linkage |
| 23 | Deposition in the physics sub-model |
| 24 | Forced mortality scalar |
| 25 | Forced growth scalar |
| 26 | FSPB additions |
| 27 | C and P code |
| 28 | SS3 tiered code |
| 29 | External scaling |
| 30 | External population model |

: Values for the [debug]{style="color: orange;"} parameter. {#tbl-debug-values tbl-colwidths=[15,85]}

This list changes as new debugging options are added. For the current list, see the **atlantisboxmodel.h** file (around line 750) in the Header files subfolder of the **atlantismain** library, or the [Atlantis wiki](https://atlantis-ecosystem-model.github.io/atlantis-wiki/posts/new-debug-flag-option-included-debug-24.html).

List and description of parameters in the *run.prm* file.

:::