# Force Parameters {#sec-force-parameters}

Atlantis can take a lot of externally forced tracer and parameter values. Details on such forcing files are given in the *force.prm* file.

The minimum *force.prm* file will contain the pathname and load information for a hydrodynamics forcing file and nothing else. However, in most models a lot more of physical, ecological and socio-economic processes are forced and pathnames for all these files will be required in *force.prm*. See @tbl-forcing-parameters-3 below for the list and application examples of different forcing options.

::: {.callout-caution}
**Absolute time in Atlantis: model time, hydro time and TS time**                                                

The time (t) entry in the *initial_conditions.nc* file indicates the actual absolute time in calendar years that marks the start date and time of the model simulation. For example: 

t:units = \"seconds since 2000-01-01 00:00:00 +10\"

This indicates that this model starts at midnight on the first of January 2000. This is the main Atlantis time (called **model time**). The hydrodynamics forcing file also has its own absolute start time, which is called **hydro time**; this does not have to match with the model time. For example, the hydrodynamics data might have five calendar years and start from 2002 July. Atlantis will try to match the model time to the hydro time. In the example, above Atlantis will start the run by loading in the hydrodynamics beginning in January not July and run from there, matching the month of the year when rewinding the hydro data. 

The time series forcing files also have a parameter indicating the absolute time of the start (**TS time**). For example, the forcing data may start from 1990 July. On read in Atlantis will by default convert these times into model time, skipping that part of the time series that occurs before model time begins. In the example here, the first 10 years of TS data will be skipped, and only the forcing information from year 11 will be used. Alternatively, if TS time starts later than the model time, Atlantis will run the simulation without any forcing until the model time matches the TS time. 

Users have an option to match the TS time not to the model time but to the hydro time. This is done by setting [ts_on_hydro_time]{style="color: orange;"}=1. If [ts_on_hydro_time]{style="color: orange;"}=0 then the default will be used (matching to model time). However, keep in mind that if TS time is matched to hydro time any rewinding of hydrodynamics data will also mean the rewinding of the forcing data. For example, if 50 years of forcing data is available and the model runs for 50 years all forcing will be used if TS and model times match. However, if TS is matched to hydro time and the hydrodynamics is rewound every 5 years, then only 5 years of TS values will be used before the TS file is rewound along with the hydrodynamics data.

Note that the rewinding of TS file described above (done when [ts_on_hydro_time]{style="color: orange;"}=1) is not the same as specific rewind options associated with most TS files. The specific TS rewind parameters apply when the time series of the run (either on model or hydro time) exceeds the time series given the TS file. See details on the TS file format below.
:::

It is recommended that users download the sample [South East Tasmanian (SETas) model](https://atlantis-ecosystem-model.github.io/atlantis-wiki/sample-input-files.html) input files that give details on the structure of the forcing and other parameter files. The table below lists currently available forcing options.


::: {.callout-note}
**Format of the time series (TS) forcing files** 

The TS forcing files have a standard input format read by Atlantis. At the top of the file the user can provide a comment on what the file represents (marked by a single \# at the start of each line). Then the user needs to provide a description of variables in each column of the TS data file (Atlantis needs this to know what the variable name is, its units and missing value marker). Atlantis recognises these entries as column description with \## at the start of each line. If a single \# is given Atlantis will assume it is a comment and ignore it, so if you are having read-in issues make sure you have all column descriptions beginning with ##. Underneath this header section is the actual data table in columns. The number of columns in the data should be the same as the number of column descriptions.

The first column always indicates time and is given in the units defined (typically days). The data in the TS file can be given at longer time intervals, such as every 30 or every 365 days. If forcing data is not given for every timestep of the model Atlantis will either use the last valid value (i.e. the last value before the gap in the data) or interpolate between the last valid value and the next (future) value in the time series file. The handling of patchy data is determined by the [typeXXXXts]{style="color: orange;"} parameter, such as [typeCatchts]{style="color: orange;"} or [typeDiscardts.]{style="color: orange;"} If [typeXXXXts]{style="color: orange;"} is 1 the same value is used throughout the period between two forcing time steps, if [typeXXXXts]{style="color: orange;"} is 0 then Atlantis will interpolate the value. Not all forcing files have the [typeXXXXts]{style="color: orange;"} parameter and if this parameter is not available it means that **Atlantis will interpolate values**. For example, if the value on day 1 was 10 and the value on day 5 is 50, setting [typeXXXXts]{style="color: orange;"} to 1 means that on day 2, 3 and 4 the value returned will be 10, while on day 5 value it will be 50. Setting [typeXXXXts]{style="color: orange;"} to 0 means that the value returned on day 2 is 20, day 3 value is 30 and day 4 value is 40. See further details about the interpolation [here](https://atlantis-ecosystem-model.github.io/atlantis-wiki/43155575.html)

Make sure you choose the correct value for the rewind parameter, as that will determine what happens if forcing file time series is shorter than the model run: rewind=0 means that the last value will be used for the remainder of the run, rewind=1 means that the time series will be reused from the start. More details on the structure of different TS files can be found [here](https://atlantis-ecosystem-model.github.io/atlantis-wiki/posts/group-size-scale-time-series-input-non-compulsory-change-to-.html).

```
# THIS FIRST LINES ARE A COMMENT ON THE SOURCE OF THE DATA
# GDP time series for Australia 1972 to 2008 based on treasury projections in 2006 Budget
# Fuel cost time series from autoregressive cost model based on Australian TACC diesel cost data
#
# - EVERYTHING BELOW IS READ BY ATLANTIS AND MUST BE IN A STANDARD FORM
# COLUMNS 3
## COLUMN1.name Time
## COLUMN1.long_name Time
## COLUMN1.units days since 1972-01-01 00:00:00 +10
## COLUMN1.missing_value 0
##
## COLUMN2.name GDP
## COLUMN2.long_name GDP
## COLUMN2.units dollars
## COLUMN2.missing_value 0
##
## COLUMN3.name FuelCost
## COLUMN3.long_name FuelCost
## COLUMN3.units dollars
## COLUMN3.missing_value 0
##
1 0.206 0.64
2 0.207 0.68
3 0.208 0.69
4 0.209 0.65
5 0.204 0.64
6 0.202 0.63
7 0.210 0.62
```
**NOTE:** If you are having issues reading a TS file
1)  Make sure there are no extra spaces or tabs after the name of the column (this can sometimes happen if you have created your TS file in excel and then pasted on to a text editor). Atlantis should now ignore those spaces, but in the past it was an issue. 
2)  Make sure the model is space not tab delimited. Again Atlantis should now be able to read either option, but just to be careful. 
3)  If a collaborator created the file for you and they use a different operating system, make sure the file is in the correct file type for your machine (in text-pad, text wrangler etc check that it is a windows type if you are on a windows machine and linux if you do not use windows). See @sec-input-files for file conversion details.
:::

| **Forcing** | **Parameters needed in *force.prm*** |
|:------------|:-------------------------------------|
| **Forcing of physical parameters** | |
| Hydrodynamics | This is the minimum forcing required to run Atlantis. See @sec-forcing-files for details on hydrodynamic forcing files.<br><br>[nhdfiles]{style="color: orange;"} gives the number of hydrodynamics files that will be supplied (read in). It is possible to put all the forcing time series into one file, but these files can get very big. Therefore, it is often easier to split the series into a number of smaller files. Atlantis will read these files in the order given, using forcing data from the first file, then from the second one and so on. Once the data from the last file is used, Atlantis will return to the first file and start reading from there again.<br><br>The hydrodynamics files are automatically looped. For other forcing input files an additional parameter (\_rewind) indicates whether the forcing data should be looped when the time series finishes (=1) or stay on the last value (=0).<br><br>Note that the pathway to the file is tagged for Atlantis by the parameter name [hdN.name]{style="color: orange;"} where N indicates the number of the file, remembering that numbering in C (and thus Atlantis) starts at 0. So [hd0.name]{style="color: orange;"}, [hd1.name]{style="color: orange;"}, [hd2.name]{style="color: orange;"} and so on.<br><br>For example, the following would indicate there are 2 hydrodynamic files and that they are located in the directory the model is being run from:<br><br>[nhdfiles]{style="color: orange;"} 2<br>[hd0.name]{style="color: orange;"} hydrofile1.nc<br>[hd1.name]{style="color: orange;"} hydrofile2.nc<br><br>The following indicate the files are stored in the inputs sub-directory (a directory one level down from the run directory):<br><br>[hd0.name]{style="color: orange;"} inputs/hydrofile1.nc<br>[hd1.name]{style="color: orange;"} inputs/hydrofile2.nc<br><br>Finally if the inputs folder is in the directory that is at the same level as the run directory then the path to the hydrodynamics files should read as:<br><br>[hd0.name]{style="color: orange;"} ../inputs/hydrofile1.nc<br>[hd1.name]{style="color: orange;"} ../inputs/hydrofile2.nc<br><br>For more information on how to indicate a path see, for example, this [Wikipedia site](https://en.wikipedia.org/wiki/Path_%28computing%29). |
| Temperature | Atlantis can calculate the temperature dynamically, but most models use temperature forcing from more accurate hydrodynamic models. See @sec-forcing-files for details of temperature forcing files. The layout of the list of files is as for the hydro file — with as many files listed as given by the [ntempfiles]{style="color: orange;"} parameter.<br><br>[use_tempfiles]{style="color: orange;"} 1 — if temperature forcing (NC files) are being used<br>[ntempfiles]{style="color: orange;"} N — where N is the number of files being provided<br>[Temperature0.name]{style="color: orange;"} temp1.nc — the path and filename of the first file<br>[Temperature1.name]{style="color: orange;"} temp2.nc — the path and filename of the second file<br>[Temperature2.name]{style="color: orange;"} temp3.nc — the path and filename of the third file<br>...<br>[temp_rewind]{style="color: orange;"} 0 — flag indicating whether to rewind (loop over) the temperature forcing data (1) or not (0) |
| Salinity | Atlantis can also load in salinity forcing from more accurate hydrodynamic models. SEc @sec-forcing-files for details of salinity forcing files.<br><br>The layout of the salinity parameters and file name list is as for temperature.<br><br>[use_saltfiles]{style="color: orange;"} 1<br>[nsaltfiles]{style="color: orange;"} N<br>[Salinity0.name]{style="color: orange;"} salt1.nc<br>[Salinity1.name]{style="color: orange;"} salt2.nc<br>...<br>[salt_rewind]{style="color: orange;"} 0 (or 1) |
| pH forcing | If pH is tracked, it is possible to calculate it dynamically or provide external forcing values from specific models. The pH forcing is provided through spatial NC files in the same way as for temperature and salinity.<br><br>[use_phFiles]{style="color: orange;"} 0<br>[npHfiles]{style="color: orange;"} N<br>[pH0.name]{style="color: orange;"} pHforceA.nc<br>[pH1.name]{style="color: orange;"} pHforceB.nc<br>[pH_rewind]{style="color: orange;"} 0 |
| Forcing of other tracers | It is possible to force any other tracers with external data. See details on the wiki [here](https://confluence.csiro.au/display/Atlantis/2013/07/10/Read+in+forcing+data+for+tracers). When new data is read in at the end of the timestep any existing value is overwritten with the value from the NC forcing file. This has been used for contaminants and for oxygen (e.g. when internal Atlantis calculations were not reproducing oxygen dynamics sufficiently well). This is a useful option, but should be used with care for any tracers that contain N (and P or C if tracking those tracers), as it can violate the assumption of conservation of matter.<br><br>[use_force_tracers]{style="color: orange;"} 1 — this flag indicates whether additional tracer forcing files should be read in (1) or not (0)<br>[nforceTracers]{style="color: orange;"} N — where N is the number of tracers that will be forced<br>[tracerNames]{style="color: orange;"} — list of tracer names (matching the names used in the *initial_conditions.nc* file) that will be forced, with each name on a new line. For example:<br><br>[nforceTracers]{style="color: orange;"} 2<br>[tracerNames]{style="color: orange;"} 2<br>Oxygen<br>Arsenic<br><br>For each tracer listed you must then give the filenames using the format:<br><br>[TRACERNAME_nFiles]{style="color: orange;"} N — where TRACERNAME is the name of the tracer and N is the number of files to be loaded<br>[TRACERNAME_File0.name]{style="color: orange;"} TRACER_1.nc — path and filename for the first forcing file for the tracer<br>[TRACERNAME_File1.name]{style="color: orange;"} TRACER_2.nc — path and filename for second file, etc.<br>[TRACERNAME_rewind]{style="color: orange;"} 0 — whether to rewind the forcing files (1) or not (0)<br><br>For example:<br><br>Arsenic_nFiles 1<br>Arsenic_File0.name Arsenic.nc<br>Arsenic_rewind 0 |
| Point sourcing of nutrients | Even though Atlantis calculates internal nutrient dynamics, it is relatively common to force additional nutrient inputs (e.g. from sewage outfalls, river mouth, upwellings etc). For example, the California Current, Guam, Gulf of Mexico and Chesapeake Bay models all use nutrient loading forced with nutrient time series (Brand *et al.* 2007; Ainsworth *et al.* 2015; Weijerman *et al.* 2015). While such inputs are mostly used to imitate nutrient inputs from sources clearly outside the model domain (e.g. rivers), they can also be used as a proxy for multi-decadal trends in ocean productivity, even if full multi-decadal oceanographic data is not available and must be 'looped'.<br><br>Externally forced nutrient sources (or sinks if negative values are given) are provided as TS files.<br><br>[npointss]{style="color: orange;"} N — where N is the number of externally supplied point source/sink files<br><br>For each TS file the following details must be given:<br><br>[pss0.name]{style="color: orange;"} XXXX — where XXXX is a meaningful name for the point, such as a river name, used so the modeller knows what this point represents; this name is NOT used by Atlantis<br>[pss0.location]{style="color: orange;"} X Y Z — e.g. 3951091.3 1789202.7 **-1**<br>[pss0.data]{style="color: orange;"} PSSTS1.ts — path and filename of the forcing TS file<br>[pss0.rewind]{style="color: orange;"} 1 — whether to rewind the forcing file (1) or not (0) |

: Forcing parameters for Atlantis model configuration. {#tbl-forcing-parameters-1 tbl-colwidths=[20,80]}

::: {.callout-caution}
**Note!** The location values (X Y Z) have three values — coordinates to input the point source (3951091.3 1789202.7) and the depth **(-1).** To make sure the point source is deposited in the desired box it is a good idea to ensure the X Y values match the "inside" point of the box as given in the BGM file (@sec-geometry-model-domain).

The **last number in the location is very important** as it will determine the correct reading of the forcing data. For point source data the depth must be a negative number for it to be deposited in the water. Other time series forcing files (e.g. for catch) follow a similar format to the PSS files — requiring a name, location, data (filename) and rewind flag. However, **for these forcing files the third number gives the box ID number (from BGM file, @sec-geometry-model-domain) not a depth.**
:::

| **Forcing** | **Parameters needed in *force.prm*** |
|:------------|:-------------------------------------|
| Bottom stress | Bottom stress values are used to calculate resuspension and additional macrophyte mortality due to wave action. Atlantis can calculate bottom stress values dynamically, but if processes affected by bottom stress are a focus of the study it is recommended to force stress externally from more precise hydrodynamic models. At present there is no flag to indicate whether this file will be loaded (future releases are likely to switch to a flag as for temperature and salinity, e.g. use_stressfiles). At present if the [BottomStress]{style="color: orange;"} tag is in the *force.prm* then the listed file will be read automatically.<br><br>[BottomStress]{style="color: orange;"} stress.nc — the path and filename of the stress NC input file.<br><br>If you do not wish to use bottom stress simply omit the [BottomStress]{style="color: orange;"} entry from the *force.prm* file. |
| Precipitation and evaporation | See @sec-main-physics-routine on how the precipitation forcing data is used. As in the case of bottom stress, precipitation and evaporation are forced through spatial NC files. They will be loaded if the tag name is present in the *force.prm* file (if not provided the model will not look to load the files).<br><br>[Precipitation]{style="color: orange;"} rain.nc — path and filename for the precipitation<br>[Evaporation]{style="color: orange;"} evap.nc — path and filename for the evaporation<br><br>**These files will not rewind.** |
| Solar radiation | Solar radiation can be calculated dynamically by Atlantis or can be forced through a time series TS file. In the latter case (TS file used) the same value is used for the entire model domain. If you do not wish to load a solar TS file do not provide a [Solar_radiation]{style="color: orange;"} entry in *force.prm* and set [lim_sun_hours]{style="color: orange;"} to 1 in the *biology.prm* file. As with bottom stress the solar radiation file will be loaded if the tag name is present in the *force.prm* file.<br><br>[Solar_radiation]{style="color: orange;"} solar.ts — path and filename for the solar forcing file<br>[Solar_radiation_rewind]{style="color: orange;"} 0 — flag indicating whether to rewind the data file (1) or not (0) |
| CO2 concentrations | Time series of atmospheric CO2 concentrations. This is used to dynamically calculate pH values and is required if [track_pH]{style="color: orange;"}=1 in *run.prm*.<br><br>See further details on the wiki [here](https://confluence.csiro.au/display/Atlantis/2012/10/19/Handling+effects+of+acidification). |
| Ice | If ice is modelled dynamically, the user must provide ice forcing data. See details on the wiki [here](https://confluence.csiro.au/display/Atlantis/Ice+Forcing+files). |
| **Forcing of ecological parameters** | |
| Forcing of recruitment | Recruitment can be forced in two ways, see details on the wiki [here](https://confluence.csiro.au/display/Atlantis/Recruitment+forcing).<br><br>The first is to use a single recruitment time series across the entire model domain. To do this the tag [Recruitment_time_series]{style="color: orange;"} must be added to the *force.prm* file:<br><br>[Recruitment_time_series]{style="color: orange;"} filename.ts — path and filename for the time series<br><br>This time series provides a TS file of recruits entering the entire model domain. Box specific forcing of recruitment is also allowed as described in the link above.<br><br>The second way is to allow for time series of recruitment to be read in for specific boxes. To do this set:<br><br>[nMultRects]{style="color: orange;"} N — the number of boxes where recruitment time series will be provided<br>[typeMultRects]{style="color: orange;"} 1 — the type of time series; whether to use the last value (0) or interpolate between values (1)<br><br>Then for each of the N boxes you need to provide the following:<br><br>[MultRects0.name]{style="color: orange;"} Meaningful_name<br>[MultRects0.location]{style="color: orange;"} X Y BOXID — e.g. 4924432.61 3298510.07 94<br>[MultRects0.data]{style="color: orange;"} filename1.ts — path and filename of the TS file for box BOXID<br>[MultRects0.rewind]{style="color: orange;"} 0 — whether to rewind the file (1) or not (0)<br>[MultRects1.name]{style="color: orange;"} Meaningful_nameB<br>[MultRects1.location]{style="color: orange;"} X Y BOXID2<br>[MultRects1.data]{style="color: orange;"} filename2.ts<br>[MultRects1.rewind]{style="color: orange;"} 0<br>... |
| Recruitment scaling | Recruitment can also be scaled by a time series of species-specific scalars provided in a time series (TS) file. To use this option include the tag [Recruitment_enviro_forcing]{style="color: orange;"} in the *force.prm* file.<br><br>[Recruitment_enviro_forcing]{style="color: orange;"} scalarfile.ts — path and filename for the time series<br><br>More details are given on the [wiki](https://confluence.csiro.au/display/Atlantis/Recruitment+forcing). |
| Recruit size | Representing differential survival can be done in two ways, both of which use a time series file. To activate these set [flag_modify_KWSR]{style="color: orange;"} in the *biology.prm* file to a value greater than 0. In both cases KWRR will be reset so that it is KWSR \* X_RS. If [flag_modify_KWSR]{style="color: orange;"} is set to 1 then the model will load a time series of multipliers to apply to the constant KWSR supplied for the group in the *biology.prm* file. If [flag_modify_KWSR]{style="color: orange;"} is set to 2 then the model will load a time series file of values to use for KWSR.<br><br>In both cases the file for KWSR is supplied in *force.prm* as follows:<br><br>[KWSR_forcing]{style="color: orange;"} KWSR_filename.ts |
| Larval connectivity matrix | To activate set [use_larvalfiles]{style="color: orange;"} 1 in the *force.prm* and then provide the filename of the connectivity matrix per species using larval dispersal:<br><br>[Larval0.name]{style="color: orange;"} connectfile.nc — path and filename for the connectivity matrix NC file<br>[Larval_rewind]{style="color: orange;"} 0 — flag indicating whether to rewind the file (1) or not (0)<br><br>The NC file must contain an entry [XXX_Connectivity]{style="color: orange;"} (where XXX is the group code from the *functional_groups.csv* file). These entries are annual connectivity matrices. If there are fewer entries than there are years in the run then the rewind flag will dictate whether the file is rewound or not.<br><br>This is recent functionality that has not been widely used. It allows entering a larval dispersal matrix. See further details [here](https://confluence.csiro.au/display/Atlantis/Recruitment+Options).<br><br>If you want this connectivity matrix to be used completely in place of [recruit_hdistrib]{style="color: orange;"} (rather than in combination with it) then set the flag [larvae_connect_only]{style="color: orange;"} to 1. |
| Linear mortality scaling | External scalar on linear mortality (*mortsc* in chapters on Ecology routines) — can also be supplied as an additional site specific mortality rate rather than a scalar. This can be provided as a TS file or spatially with box-specific values as an NC file.<br><br>See details [here](https://confluence.csiro.au/pages/viewpage.action?spaceKey=Atlantis&title=External+Mortality%2C+Growth+and+Recruitment+Scaling) on how the external mortality scaling is set and calculated. |
| Scaling of size, growth rate or maturation proportion | The scaling of growth and maturation has been used to explore ecological consequences of long-term trends in life-history traits (e.g. Audzijonyte et al. 2013; Audzijonyte & Kuparinen 2016).<br><br>The scaling is forced through external forcing scalars on size (SN and RN values), growth rate (mum parameter) or maturation (FSPB parameter). The scalars are applied by scaling the existing values. See further details on size change forcing [here](https://confluence.csiro.au/display/Atlantis/2010/07/12/Group+size+scale+time+series+input+-+non-compulsory+change+to+forcing+input+file) and on mum and FSPB scalar [here](https://confluence.csiro.au/display/Atlantis/2011/03/03/Changing+growth+rates+and+FSPB+over+time). |

: Additional forcing parameters for Atlantis model configuration. {#tbl-forcing-parameters-2 tbl-colwidths=[20,80]}

### Forcing of fisheries and socio-economic parameters

It is possible to provide forced catches, discards, effort and other socio-economic parameters. Forced catches and discards, in particular, have been used to parameterise the model and emergent biomasses given the known catch history. See, for example, details in [Fulton et al. 2007 and Link et al. 2011](https://atlantis-ecosystem-model.github.io/atlantis-wiki/useful-reading.html). The catch and discard forcing files are provided as box-specific species-specific time series. At each timestep Atlantis will then take the forced catch from the species biomass. See further details in the description of the Harvest submodel. 

| **Forcing** | **Parameters needed in *force.prm*** |
|:------------|:-------------------------------------|
| Catch | To force catches use the following parameters:<br><br>[nCatchts]{style="color: orange;"} N — the number of catch force time series (TS) files<br>[typeCatchts]{style="color: orange;"} 1 — whether to use the last value (1) or interpolate (0) between the two forcing time steps<br><br>This is followed by the actual box-specific forcing file information. Atlantis will attempt to take the forced catch from the specified box. If not enough biomass is available Atlantis will first try to take the biomass from younger age classes, then may look to neighbouring boxes (depending on the [flagimposecatch]{style="color: orange;"} setting in *harvest.prm*) and if it still can't fill it will hold it over ("carry over") and add the remaining amount to the biomass to take the following day. If at the end of the year there still remains catch that cannot be taken it is noted in the *log.txt* file and the "carry over catch" is zeroed to start again in the new year.<br><br>[Catchts0.name]{style="color: orange;"} meaningful_name — e.g. box0catch; this is NOT used by Atlantis<br>[Catchts0.location]{style="color: orange;"} X Y BOXID — e.g. 370889.3287 -717418.8373 0. This is the x, y and box ID indicating the box where the catch will be extracted. It is safest to use the "inside" point of the box BOXID as given in the BGM file (@sec-geometry-model-domain on details about model geometry)<br>[Catchts0.data]{style="color: orange;"} catchfile1.ts — path and filename of the catch TS file<br>[Catchts0.rewind]{style="color: orange;"} 0 — whether to rewind the data file (1) or not (0) |
| Discard | The entry format is as for catches above, but instead of catches provide discard values for the specified boxes:<br><br>[nDiscardts]{style="color: orange;"} N — the number of time series (TS) files<br>[typeDiscardts]{style="color: orange;"} 1 — whether to use the last value (1) or interpolate (0) between the two forcing time steps<br>[Discardts0.name]{style="color: orange;"} meaningful_name<br>[Discardts0.location]{style="color: orange;"} X Y BOXID<br>[Discardts0.data]{style="color: orange;"} disfile1.ts — path and filename of the TS file<br>[Discardts0.rewind]{style="color: orange;"} 0 — whether to rewind the data file (1) or not (0) |
| MPA | This forcing file "closes" a proportion of the box to fishing (with the columns in the TS file being the closure per fishery), simulating marine protected areas (MPA). This is used in place of the MPA vectors in *harvest.prm* and is useful where MPAs vary through time. Further details are provided in the Harvest submodel description.<br><br>[nMPAts]{style="color: orange;"} N — the number of time series (TS) files<br>[typeMPAts]{style="color: orange;"} 1 — whether to use the last value (1) or interpolate (0) between the two forcing time steps<br>[MPAts0.name]{style="color: orange;"} meaningful_name<br>[MPAts0.location]{style="color: orange;"} X Y BOXID<br>[MPAts0.data]{style="color: orange;"} mpafile1.ts — path and filename of the TS file<br>[MPAts0.rewind]{style="color: orange;"} 0 — whether to rewind the data file (1) or not (0) |
| Effort | This forcing file provides the effort time series to apply in a box (with the columns of the TS file giving the effort per fishery). Further details are provided in the Harvest submodel description.<br><br>[nEffortts]{style="color: orange;"} N — the number of time series (TS) files<br>[typeEffortts]{style="color: orange;"} 1 — whether to use the last value (1) or interpolate (0) between the two forcing time steps<br>[Effortts0.name]{style="color: orange;"} meaningful_name<br>[Effortts0.location]{style="color: orange;"} X Y BOXID<br>[Effortts0.data]{style="color: orange;"} effortfile1.ts — path and filename of the TS file<br>[Effortts0.rewind]{style="color: orange;"} 0 — whether to rewind the data file (1) or not (0) |
| Residuals | These time series provide the price residuals per market if using the economics model and forcing historical prices. One time series is required per market, with the columns providing the residual values per species.<br><br>[nResidualts]{style="color: orange;"} N — the number of time series (TS) files<br>[typeResidualts]{style="color: orange;"} 1 — whether to use the last value (1) or interpolate (0) between the two forcing time steps<br>[Residualts0.name]{style="color: orange;"} market_name — NOT used by Atlantis<br>[Residualts0.location]{style="color: orange;"} X Y BOXID — x, y location and box ID for the port which supplies the market<br>[Residualts0.data]{style="color: orange;"} resid_file1.ts — path and filename of the TS file<br>[Residualts0.rewind]{style="color: orange;"} 0 — whether to rewind the data file (1) or not (0) |
| Economic statistics | Economic statistics include GDP and fuel costs. They are used in the economically driven dynamic fishing calculations. They are not box specific, but just time series values that apply across the entire model.<br><br>[nEconts]{style="color: orange;"} 1 — typically 1 or 0; only non-zero if using the economic effort model<br>[typeEconts]{style="color: orange;"} 0 — whether to use the last value (1) or interpolate (0) between the two forcing time steps<br>[Econts0.name]{style="color: orange;"} meaningful_name — NOT used by Atlantis<br>[Econts0.location]{style="color: orange;"} X Y BOXID — x, y and box ID of any dynamic box in the model; by convention set to the values for the box with the largest market port<br>[Econts0.data]{style="color: orange;"} econ_file1.ts — path and filename of the TS file<br>[Econts0.rewind]{style="color: orange;"} 0 — whether to rewind the data file (1) or not (0) |

: List and description of external forcing options available in Atlantis. {#tbl-forcing-parameters-3 tbl-colwidths=[20,80]}

::: {.callout-caution}
**Note!** Remember that the third number of the location is the box ID number (from BGM file, @sec-geometry-model-domain). **It is very important to give this number correctly or else Atlantis will not read or apply the forcing inputs correctly.**
:::
