---
title: "9. PRIMARY PRODUCER PROCESSES"
---

The main Atlantis model has six different types of primary producers, including two sizes of phytoplankton (large phytoplankton LG_PHY and small phytoplankton SM_PHY), mixotrohic dinoflagellates (DINOFLAG), microphytobenthos (MICROPHTYBENTHOS) and two epibenthic groups (seagrasses SEAGRASS and other phytobenthos PHYTOBEN). In models including ice, specific ice primary producers are modelled. Simialrly in models that dynamically represent land, the user can define terrestrial vegetation (primary producer) groups, which are restricted to land (e.g. MANGROVE, MARSH, with crops and agriculture also available as in industry if the land use model option is used). The description below will focus on the main model only.

## **9.1. Fluxes in primary producers**

In primary producer pools the flux is determined by growth (*G~PP~*), natural mortality (*M~PP~*) and grazing (predation) (*Gr~PP,i~*). In addition, there is an optional encystment at certain times of the year or when temperatures (*Ec~out~*) reach a certain trigger level. Transfer back from cysts occurs when conditions are suitable (*Ec~in~*).

Four types of primary producer groups are tracked separately in both the water column and sediments (SM_PHY, LG_PHY, DINOFLAG, MICROPHTYBENTHOS). Two groups are restricted to the epibenthic layer (PHYTOBEN, SEAGRASS). The general flux equation is

$$\frac{d(PP)}{dt} = G_{PP} - M_{PP} - \sum_{i = predators}^{}{Gr_{PP,i}} - Ec_{out} + Ec_{in}$$

::: {.callout-caution}
**NOTE!** Not all processes are executed in all layers.  

**Primary producer GroupType processes in water column, sediments and epibenthos** 

For SM_PHY, LG_PHY, DINOFLAG:

**In the water column**: the processes executed are growth (primary production) and mortality due to lysis and grazing.
**In the sediments**: there is no primary production (only mixotrophic production in DINOFLAG), no lysis mortality and no grazing, only linear mortality. 

For MICROPHTYBENTHOS: 
**In the water column and sediments**: growth (primary production) and mortality due to grazing are carried out in both locations, with mortality due to lysis in water column or linear mortality in sediments.

For SEAGRASS and PHYTOBEN: 
**In epibenthic layer**: growth (primary production), linear and extra mortality and mortality due to grazing are all executed.
:::


::: {.callout-caution}
**Role and origin of microphytobenthos in Atlantis**  

Most ecosystem models do not explicitly model microphytobenthos, which consists of small epibenthic primary producers. The Port Philip Bay Integrated Model (PPBIM) (Muray and Parslow 1997), which is used as a basis for simulating lower trophic level dynamics in Atlantis, included microphytobenthos, because it was well studied in the Port Phillip Bay and its production was shown to be significant. Other estuarine models also use microphytobenthos given its important role in those kinds of ecosystems. However, for the majority of coastal Atlantis models the group is not used due to the limited amount of data available for parameterisation and the deeper water depths, where it plays a less important role.
:::

## **9.2. Primary producer growth**

The equations and processes governing primary production in Atlantis have been adopted from the PPBIM model of [Murray and Parslow (1997)](https://confluence.csiro.au/display/Atlantis/Useful+Reading?preview=/43155482/341447378/Link_et_al_2011_NEUS_tech_memo.pdf). Primary production processes are executed by *Primary_Production()* routine in **atprocess.c**

Growth of a primary producer *pp* is determined by **multiplying** the biomass of *pp* by the maximum specific growth rate (*mum*) and by three additional potentially limiting factors:

1. nutrient limitation factor
2. light limitation factor
3. space limitation factor for benthic macrophytes
4. optional eddy scalar, representing enhancement of primary production by eddies
5. optional pH scalar, accounting for possible effects of acidification on primary production

$$G_{pp} = mum \cdot B_{PP} \cdot \delta_{light} \cdot \delta_{nutrient} \cdot \delta_{space} \cdot \delta_{eddy} \cdot pHscalar$$

The *mum* parameter defines the maximum growth rate per day (mgN day^-1^).


::: {.callout-caution}
**Multiplicative model for nutrient and light co-limitation (from Murray and Parslow, 1997, page 26):** 

"Multiplicative models for nutrient and light co-limitation have been widely used (Fasham et al. 1990). A potential problem with multiplicative interactions involving several factors is that predictive growth rates become very low when each factor is moderately limiting. An alternative, Liebig\'s law of the minimum (ie. multiply mum by the smallest factor) is more often applied to interactions among multiple nutrients." 

Atlantis has different options to design limitation by different nutrients (N, Si and P if phosphorus is tracked), set by the flagnut parameter, with choices of multiplicative or Leibig (minimum nutrient) limitation. However, this does not apply to combined limitation by nutrient, light and space, where simple multiplication is used. The quote above suggests caution when applying multiple limitations on growth, and careful assessment of whether the multiple impacts do not lead to overly constraining limitation.
:::

### ***9.2.1. Primary producer nutrient limitation***

The **nutrient limitation** *δ~nutrient\ ~*scalar in case of limitation based on N only is calculated as

$$\delta_{nutrient} = \frac{DIN}{KN + DIN}$$

where **DIN = NH3+NO3** (ammonia and nitrate concentration) and *KN* is the half saturation constant of nutrient uptake (KN_XXX) in mgN m^-3^

Nutrient limitation is calculated by the *Nutrient_Lim()* routine in **atprocess.c**

When phytoplankton is limited by multiple nutrients, such as N and Si in the case of diatoms, the choice of limitation equation is set by the flagnut parameter. This parameter calls three types of nutrient limitation options -- Leibig, multicative, and the ERSEM WQI based option. Only the first two options have been more widely used, whereas the third version has been implemented only for testing purposes. The nutrient limitation scalar for the three options is calculated as:

$$\delta_{nutrient} = \min\left( \frac{DIN}{KN + DIN},\frac{Si}{KS + Si} \right)\ \ \ \ \ \ \ \ \ \ \ \ \ if\ Leibig\ limitation\ is\ used\ (flagnut = 0)$$

$$\delta_{nutrient} = \sqrt{\frac{DIN}{KN + DIN} \cdot \frac{Si}{KS + Si}}\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ if\ multicative\ limitation\ is\ used\ (flagnut = 1)$$

$$\delta_{nutrient} = \frac{2}{\left( \frac{DIN}{KN + DIN} + \frac{Si}{KS + Si} \right)}\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ if\ WQI\ \ limitation\ is\ used\ (flagnut = 2)$$

For illustration, assuming a hypothetical case of DIN and Si concentrations of 100 mg m^-3^ and half saturation values for N and Si at 50 mg m^-3^ and 20 mg m^-3^ the three limitation cases would results in scalars of 0.67, 0.75 and 1.41.

Atlantis has an optional nutrient limitation for one additional tracer of micronutrients (currently used for iron). This option is set when flagmicro=1. If micronutrient limitation is used, half-saturation constants (KF_XXX) should be provided for all primary producer groups. Limitation by additional nutrients will be done according to the flagnut option described above.

In models that track P and C (TrackAtomicRatio =1 in *run.prm* file) primary production will also be limited by P and C. Further details are available on the [wiki](https://confluence.csiro.au/display/Atlantis/2013/04/23/New+Phosphorus+tracking).

### ***9.2.2. Primary producer light limitation***

Photosynthesis in the model is potentially light-limited and the available suitable light (W m^-2^) -- the photosytenthically active radiation (PAR) - in the water column and at the sediment surface is modelled explicitly. The **light limitation** *δ~light\ ~*factor is calculated in *Light_Lim()* in **atproces.c** as:

$$\delta_{light} = \min\left( \frac{IRR}{KI},1 \right)\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ if\ light\ adaptation\ is\ not\ used\ (flaglight = 0)$$

where *IRR* is the amount of light available for the photosynthesis and *KI* is the light saturation coefficient (KI_XXX) in W m^-2^.

Atlantis allows for **light adaptation** of primary producers to be represented, which is intended to capture their ability to rapidly adapt to different light conditions. It is used when flaglight = 1 and requires four additional parameters (KIOP_min, KIOP_shift, KI_avail, K_addepth), used to calculate *optIRR* in *Box_Light_Process()* in **[atbiophysics.c]{.underline}**

If light adaptation is used the light limitation is calculated as

$$\delta_{light} = \min\left( \frac{IRR}{KI + optIRR},1 \right)\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ if\ light\ adaptation\ is\ used\ (flaglight = 1)$$

The amount of light falling on the surface of the top layer is either provided through external time series or calculated in Atlantis depending on the lim_sun_hours setting (described in chapter 5, Physics).

The **light attenuation** *Kd* through the water column (described in Fulton 2001) defines the availability of light to primary producers at different depths and is calculated as

$$Kd = k_{w} + k_{IS} + k_{PN} \cdot \sum_{i = phytopl}^{}{B_{i} + k_{DON} \cdot B_{DON} + k_{DL} \cdot \left( B_{DL} + B_{DR} \right) + k_{SED} \cdot B_{SED}}$$

The equation shows that light attenuation is simply defined by the background blue water light absorption coefficient (*k~w~*), additional light absorption due to tanins and other non-biological particulate matter that is important in coastal areas (set in *k~IS~*), and concentration or biomass of light attenuating organisms (plankton) or substances (DON, detrituts, sediments) multiplied by the corresponding light attenuation coefficient. The attenuation is caused by:

1. background light absorption by water itself (*k~w~*) -- used in the PPBIM model.
2. additional background light absorption by water due to tanins and other non-biological particulate matter that is important in coastal areas (set in *k~IS~*). Different coefficients (k_w_shallow and k_w_deep) are used for coastal and oceanic water. This second term of light absorption was not used in PPBIM but was taken from ERSEM
3. phytoplankton, with k_PN defining coefficient of light absorption by particulate matter, such as phytoplankton
4. dissolved organic nitrogen and the relevant coefficient k_DON
5. labile and refractory detritus and the coefficient k_DL
6. light absorption by suspended sediment k_SED, used only if the model is estuary (flagIsEstuary=1)

### ***9.2.3. Primary macrophyte producer space limitation***

Space limitation is only applied to epibenthic primary producers, defined by PHYTOBEN or SEAGRASS

The **space limitation** *δ~space\ ~*factor is calculated as

$$\delta_{space} = \frac{B_{PP}}{SPmax \cdot P_{area}}$$

where *SPmax* is the coefficient setting maximum biomass of the epibenthic primary producer (XXmax) in mgN m^-2^ and *P~area\ ~*is the proportion of the cell covered with suitable habitat scaled by the habitat degradation scalar (if used). Space limitation is activated using flagXXXlim.

### ***9.2.4 Effect of eddies on primary production***

The effect of eddies, or the **eddy scalar** *δ~eddy~*, on primary production is modelled by simple scaling (multiplication) using the user defined eddy_scale parameter. This dimensionless parameters is multiplied by the eddy strength in a given box to obtain *δ~eddy~*

$$\delta_{eddy} = {eddy}_{scale} \cdot {eddy}_{strength}$$

Eddy strengths for each box and each quarter are set in the *physics.prm* file (see Chapter 5.2, section III).

::: {.callout-caution}
**Effect of eddies on primary production**  

There is good evidence to suggest that the presence of eddies significantly enhances primary production through vertical water column mixing creating spatial and seasonal variation. There are two ways to add this variation in Atlantis and users are encouraged to make use of these parameters.

First, the effects of eddies on vertical mixing alone can be included through the parameters in the *physics.prm* (eddy_vertmix, eddy_S1 to eddy_S2, eddy_mixscale -- see chapter 5.2, section III). This should increase vertical mixing in the water column and bring extra nutrients to the surface.

Second, the user can add an extra scalar *δ~eddy\ ~*on primary production through the eddy_scale parameter in the *biology.prm* file. This scalar will take the eddy values and re-scale the primary production calculated for the available amount of light and nutrients based on eddy strength. The second approach assumes that additional nutrients are implicitly supplied through eddies, increasing primary production (these nutrients do not appear in the tracer values but represent just an assumed increase). This *ad hoc* approach can be taken if the model fails to accurately reflect spatial and seasonal variation in primary production, but the explicit dynamics of nutrient turnover is not resolved accurately enough to enhance primary production sufficiently through nutrient mixing alone. It is not recommended for models that focus on nutrient dynamics and lower trophic levels, but might be useful for models that focus on the dynamics at higher trophic levels and socio-economic aspects.
:::

## **9.3. Primary producer mortality**

::: {.callout-caution}
**Primary producers in water column, sediments and epibenthos** 

Primary producer processes are handled differently depending on whether they are in the water column (WC), sediments (SED) or epibenthic layer (EPI).

Four primary producer groups are tracked both in the WC and SED (SM_PHY, LG_PHY, DINOFLAG, MICROPHTYBENTHOS). Two groups are restricted to the epibenthic layer (PHYTOBEN, SEAGRASS) 

**In WC:** phytoplankton groups (SM_PHY, LG_PHY) can only grow (photosynthesise) when they are in the WC. MICROPHTYBENTHOS can grow both in the WC and in SED; for photosynthesis in the SED they use light conditions at the top of the sediment. DINOFLAG do not photosynthesis in the SED, but they can have mixotrophic feeding. Mortality expressed depends on whether it is in the WC and SED: primary producers are affected by linear mortality (mL_XXX) and optional acidification mortality in both locations, but phytoplankton (SM_PHY and LG_PHY) only suffer lysis (KLYS_XXX) in the WC. DINOFLAG and MICROPHYTOBENTHOS have all mortality terms in both locations. Both lysis and other mortality terms are separately scaled by the ***external forced optional mortality scalar***. All mortality products are transferred into the WC or SED labile detritus pools respectively.

**In EPI**: epibenthic primary producers are affected by linear mortality (mL_XXX), extra mortality due to waves or fouling (mS_XXX) and optional acidification mortality. Mortality products are transferred to the SED labile and refractory detritus pools; the split between labile and refractory detritus is determined by the FDL_benthos parameter.
:::

**Primary producer** mortality in the **water column and sediments** is modelled as

$$M_{PP} = \ \left( \left( \frac{KLYS \cdot B_{PP}}{\delta_{nutrient} + 0.1} \right) + \left( mL \cdot B_{PP} + mA \cdot B_{PP} \right) \right) \cdot mortsc$$

**Primary producer** mortality in the **epibenthic layer** is modelled as

$$M_{PP,EPI} = \ \left( mL \cdot B_{PP} + mA \cdot B_{PP} + mS \cdot B_{PP} \right) \cdot mortsc + F_{PP}$$

where *mL* (mL_XXX, day^-1^) is the linear mortality rate, *KLYS* is the lysis rate (KLYS_XXX, day^-1^), *mA* is the optional acidification mortality, *mS* is the extra mortality of large epibenthic primary producers calculated below, *B~PP~* is the biomass of the primary producer, *mortsc* is the external mortality scalar (from forcing files) and *F~PP~* is an optional fishing mortality that is sometimes applied to macroalgae.

The **extra mortality *mS*** in **large** **primary producers** includes mortality due to waves and fouling:

$$mS_{MA} = \ STRESS \cdot \ mS\_\_ MA$$

$$mS_{SG} = \ DIN \cdot \ mS\_\_ SG$$

where *mS_MA* is the algal mortality rate (day^-1^) due to abrasion by bottom stress or waves (*STRESS*), provided through external forcing or calculated in the model (see Chapter 5, Physics) and *mS_SG* is the seagrass mortality rate (day^-1^) due to fouling by epiphytes in water of high nutrient concentration, and *DIN* is the concentration of NH3 and NO3.

::: {.callout-caution}
**What is the difference between lysis and linear mortality?**                                                    
Lysis represents cell leakage and is inversely related to nutrient concentration, whereas linear mortality is just a constant mortality term. PPBIM only had the linear mortality, but ERSEM also included lysis, and both options are included in Atlantis. The users have an option to use either or both, depending on the mortality parameter values set.
:::

Finally, the extra mortality will also include any **optional acidification induced mortality**, described in details [here](https://confluence.csiro.au/pages/viewpage.action?spaceKey=Atlantis&postingDay=2012%2F10%2F19&title=Handling+effects+of+acidification) and [here](https://confluence.csiro.au/pages/viewpage.action?spaceKey=Atlantis&postingDay=2015%2F5%2F14&title=Acidification+induced+mortality) and in Chapter 13. The acidification mortality is only included if the model explicitly includes pH effects (flagmodelpH=1) and primary producers are identified as pH sensitive (flagpHsensitive_XXX=1).

Primary producer mortality is handled by *Primary_Production()* in **atprocess.c** and *Phytoplankton\_ Process()* in **atGroupProcess.c** routines.

## **9.4. Encystment of primary producers**

It is possible to include the encystment of primary producers, triggered by time of the year or temperature. This option is only modelled for groups that have isOverWinter set to 1 in the *functional_groups.csv* file and is described in further detail on the wiki [here](https://confluence.csiro.au/pages/viewpage.action?pageId=43155510).

## **9.5. Effect of temperature and salinity on primary production**

Both light saturation (KI_XXX_T15) and maximum growth rate (mum_XXX_T15) are dependent on **temperature** and will be scaled by *Tcorr* calculated based on the current water temperature as described in chapter 13.

The **salinity** effect on light saturation and maximum growth rate are optional, where the *Scorr* is applied only when:

1\) an organism is identified as sensitive to salinity, with flagSaltSensitive_XXX

2\) an organism an outside the salinity limits defined with XXX_min_move_salt and XXX_max\_ move_salt

If the two conditions are fulfilled, the *Scorr* scalar provided by the user as salt_correction_XXX parameter, is applied to KI_XXX_T15 and mum_XXX_T15 (along with the *Tcorr* described above).

## **9.6. Growth of mixotrophic primary producers**

Atlantis includes a mixotrophic dinaflagelate group DINOFLAG, the growth of which is determined by both primary production and heterotrophic consumption.

Phtosynthetic growth of DINOFLAG is as for other primary producers, although there is some increase in efficiency at low light levels, represented here by increasing effective light available via the following equation (which is only used if light levels drop below 10% of KI_XXX):

${IRR}_{sp} = KI_{XXX} \cdot \ (0.01 \cdot IRR + 0.018)$

Mixotrophic growth due to consumption is calculated by first determining potential grazing (using the standard feeding routine applied to consumers). Phagotrophic growth then tops-up photosynthetic growth to the maximum possible rate, as if nutrients were non-limiting, unless the maximum growth rate is higher than what could be physically grazed. In this way grazing leads to additional growth compared to photosynthesis alone. Unlike in other consumers mixotrophic groups have no excretion (production of NH) as the nutrients are used in the photosynthetic growth pathway.

Nutrient stress related lysis of DINOFLAG is also corrected to account for the mitigating effects of phagotrophy), with the corection dictated by the proportion of photosynthetic nutrient made up by the grazing.

---
title: "PRIMARY PRODUCTION PARAMETERS"
---

::: {.table-responsive}
| **Parameter** | **Description** |
|:--------------|:----------------|
| **Key parameters defining primary production and primary producer mortality** | |
| KN_XXX | Half-saturation constant for XXX growth on DIN (mgN m^-3^) |
| KS_XXX | Half-saturation constant for XXX growth on Si (mgN m^-3^ ) -- only important for Si limited groups, as defined in the *functional_groups.csv* file |
| KI_XXX_T15 | Light saturation of XXX at 15C (W m^-2^) - this parameter is temperature dependent (and potentially salinity dependent), and a scalar is applied based on current temperature (and salinity) conditions. |
| mum_XXX_T15 | Maximum primary producer XXX growth rate at 15C (mgN mgN^-1^ day^-1^) -- this parameter is temperature dependent (and potentially salinity dependent), and a scalar is applied based on current temperature (and salinity) conditions. |
| XXmax | Maximum biomass of large epibenthic primary producers (phytobenthos and macroalgae) (mgN m^-2^) |
| mL_XXX | Linear mortality of primary producers (day^-1^) |
| KLYS_XXX | Lysis rate of primary producers (day^-1^) |
| mS_XXX | Extra mortality of macroalgae (PHYTOBEN) due to wave action (day^-1^) |
| mS_XXX | Extra mortality of seagrasses (SEAGRASS) due to fouling (day^-1^) |
| **Further modification of primary production** | |
| flaglight | Flag indication whether light adaptation in primary producers is activated (0=no, 1=yes), It set to 1 (i.e. activated) it will increase production at low light levels, but it will also require four additional parameters: KIOP_min, KIOP_shift, KI_avail, K_addepth (see SETas model example of *biology.prm* file) |
| flag_macro_model | Flag indicated whetehr a more detailed seagrass model is activated, see details [here](https://confluence.csiro.au/display/Atlantis/2012/12/12/new+seagrass+modelling+option) (0=no, 1=yes). If the flag is set to 1 then three separate pools will be initiated and tracked for each SEAGRASS group type: main biomass, epiphyte biomass and below ground biomass |
| flagnut | Nutrient limitation form used if primary production is limited by several nutrients (0=Leibig's law where limitation is set by the most limiting nutrient; 1= multiplicative; 2=WQI) |
| flagmicronut | Flag indications whetehr there is miconutrient limitation (0=no, 1=yes)<br><br>If set to 1, half-saturation constant for gthe micronutrient (typically Fe) is required (KF_XXX) |
| eddy_scale | Coefficient scaling eddy strength impact on phytoplankton growth |
| swr_scalar | Proportion of shortwave radiation available to photosynthesis -- usually set to 0.45 |
| swr_const | Constant in the equation for the shortwave radiation available to photosynthesis -- usually set to 1367.0 |
| swr_cos_coefft | Coefficient of the cos term in the equation for the shortwave radiation available to photosynthesis -- usually set to 0.034 |
| swr_cos_offset | Offset term in the cos term in the equation for the shortwave radiation available to photosynthesis -- usually set to 0.0 |
| MB_wc | Scalar for microphytobenthos growth in the water column -- growth should be strongly reduced as it is not on the substrate (which is its primary habitat). Only important when microphytobenthos is being modelled. |

: Primary production parameters for Atlantis model configuration {#tbl-primary-production-parameters}
:::

::: {.callout-note}
**If TrackAtomicRatio is set to 1** in *run.prm* file and the model tracks N:P:C many additional parameters are required to describe P, and C effect on primary production. See details [here](https://confluence.csiro.au/display/Atlantis/2013/04/23/New+Phosphorus+tracking) and sample SETas model *biology.prm* file
:::

: []{#_Toc526762765 .anchor}Table 13. Parameters used for primary producer processes