project:
  type: book
  output-dir: _site

book:
  title: "Atlantis User Guide"
  search: true
  sidebar:
    style: "docked"
    background: light
    collapse-level: 2

  chapters:
    - index.qmd
    - user_guides/quarto_site/part1/01-foreward.qmd
    - part: "Part I - Setup, Physics, and Biology"
      chapters:
        - user_guides/quarto_site/part1/index.qmd
        - user_guides/quarto_site/part1/02-introduction.qmd
        - user_guides/quarto_site/part1/03-installation-and-running.qmd
        - user_guides/quarto_site/part1/04-geometry-of-the-model-domain.qmd
        - user_guides/quarto_site/part1/05-hydrodynamic-salinity-and-temperature-forcing-data.qmd
        - user_guides/quarto_site/part1/06-the-physics-submodel.qmd
        - user_guides/quarto_site/part1/07-definitions-of-functional-groups.qmd
        - user_guides/quarto_site/part1/08-run-parameters.qmd
        - user_guides/quarto_site/part1/09-force-parameters.qmd
        - user_guides/quarto_site/part1/10-primary-producer-processes.qmd
        - user_guides/quarto_site/part1/11-consumer-processes.qmd
        - user_guides/quarto_site/part1/12-distribution-and-movement.qmd
        - user_guides/quarto_site/part1/13-processes-in-bacterial-and-inanimate-pools.qmd
        - user_guides/quarto_site/part1/14-influence-of-environmental-factors-on-ecological-p.qmd
        - user_guides/quarto_site/part1/15-final-overview-of-ecology-routines.qmd
        - user_guides/quarto_site/part1/16-references.qmd
        - user_guides/quarto_site/part1/17-appendix-1-tips-for-calibrating-biological-model-n.qmd
    - part: "Part II - Fisheries, Management, and Economics"
      chapters:
        - user_guides/quarto_site/part2/index.qmd
        - user_guides/quarto_site/part2/01-15-fishing-mortality.qmd
        - user_guides/quarto_site/part2/02-16-management.qmd
        - user_guides/quarto_site/part2/03-17-economics.qmd
        - user_guides/quarto_site/part2/04-18-other-industries.qmd       
        - user_guides/quarto_site/part2/05-references.qmd

  appendices:
    - confluence/index.qmd
    - resources/index.qmd
    - known_limitations/index.qmd
    - contact/index.qmd

crossref:
  chapters: true

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 4
    number-sections: true