project:
  type: website

website:
  title: "Atlantis User Guide"
  navbar:
    left:
      - href: index.qmd
        text: Home
  sidebar:
    contents:
      - index.qmd
      - 01-foreward.qmd
      - 02-introduction.qmd
      - 03-installation-and-running.qmd
      - 04-geometry-of-the-model-domain.qmd
      - 05-hydrodynamic-salinity-and-temperature-forcing-data.qmd
      - 06-the-physics-submodel.qmd
      - 07-definitions-of-functional-groups.qmd
      - 08-run-parameters.qmd
      - 09-force-parameters.qmd
      - 10-primary-producer-processes.qmd
      - 11-consumer-processes.qmd
      - 12-distribution-and-movement.qmd
      - 13-processes-in-bacterial-and-inanimate-pools.qmd
      - 14-influence-of-environmental-factors-on-ecological-p.qmd
      - 15-final-overview-of-ecology-routines.qmd
      - 16-references.qmd
      - 17-appendix-1-tips-for-calibrating-biological-model-n.qmd

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 4
