# References {#sec-part2-refs}

Deporte, N., Ulrich, C., Mahévas, S., Demanèche, S., & Bastardie, F. (2012). Regional métier definition: A comparative investigation of statistical methods using a workflow applied to international otter trawl fisheries in the North Sea. *ICES Journal of Marine Science*, *69*, 331–342.

Dichmont, S. M., Fulton, E. A., Punt, A. E., Little, L. R., Dowling, N., Gorton, R., Sporcic, M., Smith, D. C., Haddon, M., & Klaer, N. (2017). *Operationalising the risk-cost-catch trade-off* (FRDC Project No. 2012-202). CSIRO Oceans and Atmosphere; Fisheries Research and Development Corporation.

Fulton, E. A., Smith, A. D. M., & Smith, D. C. (2007). *Alternative management strategies for Southeast Australian Commonwealth fisheries*. Australian Fisheries Management Authority; Fisheries Research and Development Corporation.

Hutton, T., Thebaud, O., Fulton, B., Pascoe, S., Innes, J., Kulmala, S., & Tudman, M. (2010). *Use of economic incentives to manage fisheries bycatch: An application to key sectors in Australia's Southern and Eastern Scalefish and Shark Fisheries*. Australian Fisheries Management Authority.

Kaplan, I. C., Holland, D. S., & Fulton, E. A. (2014). Finding the accelerator and brake in an individual quota fishery: Linking ecology, economics, and fleet dynamics of US West Coast trawl fisheries. *ICES Journal of Marine Science*, *71*(2), 308–319. https://doi.org/10.1093/icesjms/fst114

Little, L., Punt, A., Mapstone, B., Begg, G., Goldman, B., & Williams, A. (2009). An agent-based model for simulating trading of multi-species fisheries quota. *Ecological Modelling*, *220*, 3404–3412. https://doi.org/10.1016/j.ecolmodel.2009.08.004

Newell, R. G., Sanchirico, J. N., & Kerr, S. (2005). Fishing quota markets. *Journal of Environmental Economics and Management*, *49*, 437–462.

Pelletier, D., & Ferraris, J. (2000). A multivariate approach for defining fishing tactics from commercial catch and effort data. *Canadian Journal of Fisheries and Aquatic Sciences*, *57*, 51–65.

Squires, D., Campbell, H., Cunningham, S., Dewees, C., Grafton, R. Q., Herrick, S. F., Kirkley, J., Pascoe, S., Salvanes, K., Shallard, B., & Turris, B. (1998). Individual transferable quotas in multispecies fisheries. *Marine Policy*, *22*(2), 135–159.

van Putten, E. I., Gorton, B., Fulton, B., & Thebaud, O. (2013). The role of behavioural flexibility in a whole of ecosystem model. *ICES Journal of Marine Science*, *70*(1), 150–163. https://doi.org/10.1093/icesjms/fss175
