<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.43">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Atlantis Documentation – FISHERIES FORCING PARAMETERS</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../">
<script src="../../../site_libs/quarto-html/quarto.js"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../../../styles.css">
</head>

<body class="nav-sidebar docked nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../../index.html">
    <span class="navbar-title">Atlantis Documentation</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-user-guides" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">User Guides</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-user-guides">    
        <li>
    <a class="dropdown-item" href="../../../user_guides/quarto_site/part1/index.html">
 <span class="dropdown-text">Part I - Atlantis User Guide</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../user_guides/quarto_site/part2/index.html">
 <span class="dropdown-text">Part II - [Coming Soon]</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="../../../confluence/index.html"> 
<span class="menu-text">Confluence Wiki</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../resources/index.html"> 
<span class="menu-text">Resources</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../../user_guides/quarto_site/part1/09-force-parameters.html">8. Force Parameters</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../user_guides/quarto_site/part1/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Overview</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../user_guides/quarto_site/part1/01-foreward.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">0. Foreword</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../user_guides/quarto_site/part1/02-introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">1. Introduction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../user_guides/quarto_site/part1/03-installation-and-running.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2. Installation and Running</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../user_guides/quarto_site/part1/04-geometry-of-the-model-domain.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">3. Geometry of the Model Domain</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../user_guides/quarto_site/part1/05-hydrodynamic-salinity-and-temperature-forcing-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">4. Hydrodynamic, Salinity and Temperature Forcing Data</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../user_guides/quarto_site/part1/06-the-physics-submodel.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">5. The Physics Submodel</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../user_guides/quarto_site/part1/07-definitions-of-functional-groups.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">6. Definitions of Functional Groups</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../user_guides/quarto_site/part1/08-run-parameters.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">7. Run Parameters</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../user_guides/quarto_site/part1/09-force-parameters.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">8. Force Parameters</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../user_guides/quarto_site/part1/10-primary-producer-processes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">9. Primary Producer Processes</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../user_guides/quarto_site/part1/11-consumer-processes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">10. Consumer Processes</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../user_guides/quarto_site/part1/12-distribution-and-movement.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">11. Distribution and Movement</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../user_guides/quarto_site/part1/13-processes-in-bacterial-and-inanimate-pools.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">12. Processes in Bacterial and Inanimate Pools</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../user_guides/quarto_site/part1/14-influence-of-environmental-factors-on-ecological-p.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">13. Influence of Environmental Factors on Ecological Processes</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../user_guides/quarto_site/part1/15-final-overview-of-ecology-routines.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">14. Final Overview of Ecology Routines</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../user_guides/quarto_site/part1/16-references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../user_guides/quarto_site/part1/17-appendix-1-tips-for-calibrating-biological-model-n.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Appendix 1: Tips for Calibrating Biological Model</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
        
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">FISHERIES FORCING PARAMETERS</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Atlantis can take a lot of externally forced tracer and parameter values. Details on such forcing files are given in the <em>force.prm</em> file.</p>
<p>The minimum <em>force.prm</em> file will contain the pathname and load information for a hydrodynamics forcing file and nothing else. However, in most models a lot more of physical, ecological and socio-economic processes are forced and pathnames for all these files will be required in <em>force.prm</em>. See table 12 below for the list and application examples of different forcing options.</p>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Caution
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Absolute time in Atlantis: model time, hydro time and TS time</strong></p>
<p>The time (t) entry in the <em>initial_conditions.nc</em> file indicates the actual absolute time in calendar years that marks the start data and time of the model simulation. For example:</p>
<p>t:units = "seconds since 2000-01-01 00:00:00 +10"</p>
<p>This indicates that this model starts at midnight on the first of January 2002. This is the main Atlantis time (called <strong>model time</strong>). The hydrodynamics forcing file also has its own absolute start time, which is called <strong>hydro time</strong>; this does not have not to match with the model time. For example, the hydrodynamics data might have five calendar years and start from 2002 July. Atlantis will try to match the model time to the hydro time. In the example, above Atlantis will start the run by loading in the hydrodynamics beginning in January not July and run from there, matching the month of the year when rewinding the hydro data.</p>
<p>The time series forcing files also have a parameter indicating the absolute time of the start (<strong>TS time</strong>). For example, the forcing data may start from 1990 July. On read in Atlantis will by default convert these times into model time, skipping that part of the time series that occurs before model time begins. In the example here, the first 10 years of TS data will be skipped, and only the forcing information from year 11 will be used. Alternatively, if TS time starts later than the model time, Atlantis will run the simulation withouth any forcing until the model time matches the TS time.</p>
<p>Users have an option to match the TS time not to the model time but to the hydro time. This is done by setting ts_on_hydro_time=1. If ts_on_hydro_time=0 then the default will be used (matching to model time). However, keep in mind that if TS time is matched to hydro time any rewinding of hydrodynamics data will also mean the rewinding of the forcing data. For example, if 50 years of forcing data is available and the model runs for 50 years all forcing will be used if TS and model times match. However, if TS is matched to hydro time and the hydrodynamics is rewound every 5 years, then only 5 years of TS values will be used before the TS file is rewound along with the hydrodynamics data.</p>
<p>Note that the rewinding of TS filed described above (done when ts_on_hydro_time=1) is not the same as specific rewind options associated with most TS files. The specific TS rewind parameters apply when the time series of the run (either on model or hydro time) exceeds the time series given the TS file. See details on the TS file format below</p>
</div>
</div>
<p>It is recommended that users download the sample <a href="https://confluence.csiro.au/display/Atlantis/Sample+input+files">South East Tasmanian (SETas) model</a> input files that give details on the structure of the forcing and other parameter files. The table below lists currently available forcing options</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Format of the time series (TS) forcing files</strong></p>
<p>The TS forcing files have a standard input format read by Atlantis. At the top of the file the user can provide a comment on what the file represents (marked by a single # at the start of each line). Then the user needs to provide a description of variables in each column of the TS data file (Atlantis needs this to know what the variable name is, its units and missing value marker). Atlantis recognises these entries as column description with ## at the start of each line. If a single # is given Atlantis will assume it is a comment and ignore it, so if you are having read-in issues make sure you have all column decriptions beginning with ##. Underneath this header section is the actual data table in columns. The number of columns in the data should be the same as the number of column descriptions.</p>
<p>The first column always indicates time and is given in the units defined (typically days). The data in the TS file can be given at longer time intervals, such as every 30 or every 365 days. If forcing data is not given for every timestep of the model Atlantis will either use the the last valid value (i.e.&nbsp;the last value before the gap in the data) or interpolates between the last valid value and the next (future) value in the time series file. The handling of patchy data is determined by the typeXXXXts parameter, such as typeCatchts or typeDiscardts. If typeXXXXts is 1 the same value is used throughout the period between two forcing time steps, if typeXXXXts is 0 then Atlantis will interpolate the value. Not all forcing files have the typeXXXXts parameter and if this parameter is not available it means that <strong>Atlantis will interpolate values</strong>. For example, if the value on day 1 was 10 and the value on day 5 is 50, setting typeXXXXts to 1 means that on day 2, 3 and 4 the value returned will be 10, while on day 5 value it will be 50. Setting typeXXXXts to 0 means that the value returned on day 2 is 20, day 3 value is 30 and day 4 value is 40. See further details about the interpolation <a href="https://confluence.csiro.au/pages/viewpage.action?spaceKey=Atlantis&amp;title=External+Mortality%2C+Growth+and+Recruitment+Scaling">here</a></p>
<p>Make sure you chose the correct value for the rewind parameter, as that will determine what happens if forcing file time series is shorter than the model run: rewind=0 means that the last value will be used for the remaining of the run, rewind=1 means that the time series will be reused from the start. More details on the structure of different TS files can be found <a href="https://confluence.csiro.au/pages/viewpage.action?spaceKey=Atlantis&amp;postingDay=2010%2F7%2F12&amp;title=Group+size+scale+time+series+input+-+non-compulsory+change+to+forcing+input+file">here</a></p>
<p><strong># THIS FIRST LINES ARE A COMMENT ON THE SOURCE OF THE DATA</strong><br>
# GDP time series for Australia 1972 to 2008 based on treasury projections in 2006 Budget<br>
# Fuel cost time series from autoregressive cost model based on Australian TACC diesel cost data #<br>
<strong># - EVERYTHING BELOW IS READ BY ATLANTIS AND MUST BE IN A STANDARD FORM</strong> # COLUMNS 3 # # COLUMN1.name Time<br>
## COLUMN1.long_name Time<br>
## COLUMN1.units days since 1972-01-01 00:00:00 +10 ## COLUMN1.missing_value 0 ## ## COLUMN2.name GDP ## COLUMN2.long_name GDP ## COLUMN2.units dollars ## COLUMN2.missing_value 0 ## ## COLUMN3.name FuelCost ## COLUMN3.long_name FuelCost ## COLUMN3.units dollars ## COLUMN3.missing_value 0 ## 1 0.206 0.64 2 0.207 0.68 3 0.208 0.69 4 0.209 0.65 5 0.204 0.64 6 0.202 0.63 7 0.210 0.62</p>
<p><strong>NOTE:</strong> If you are having issues reading a TS file 1) Make sure there are no extra spaces or tabs after the name of the column (this can sometimes happen if you have created your TS file in excel and then pasted on to a text editor). Atlantis should now ignore those spaces, but in the past it was an issue. 2) Make sure the model is space not tab delimited. Again Atlantis should now be able to read either option, but just to be careful. 3) If a collaborator created the file for you and they use a different operating system, make sure the file is in the correct file type for your machine (in text-pad, text wrangler etc check that it is a windows type if you are on a windows machine and linux if you do not use windows). See chapter 2.2 for file conversion details.</p>
</div>
</div>
<div class="table-responsive">
<div id="tbl-forcing-parameters-1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-forcing-parameters-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Forcing parameters for Atlantis model configuration
</figcaption>
<div aria-describedby="tbl-forcing-parameters-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Forcing</strong></th>
<th style="text-align: left;"><strong>Parameters needed in <em>force.prm</em></strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Forcing of physical parameters</strong></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Hydrodynamics</td>
<td style="text-align: left;">This is the minimum forcing required to run Atlantis. See chapter 4 for details on hydrodynamic forcing files.<br><br>nhdfiles gives the number of hydrodynamics files that will be supplied (read in). It is possible to put all the forcing time series into one file, but these files can get very big. Therefore, it is often easier to split the series into a number of smaller files. Atlantis will read these files in the order given, using forcing data from the first file, then from the second one and so on. Once the data from the last file is used, Atlantis will return to the first file and start reading from there again.<br><br>The hydrodynamics files are automatically looped. For other forcing input files an additional parameter (_rewind) indicates whether the forcing data should be looped when the time series finishes (=1) or stay on the last value (=0)<br><br>Note that the pathway to the file is tagged for Atlantis by the parameter name hdN.name where N indictes the number of the file, remembering that numbering in C (and thus Atlantis) starts at 0. So hd0.name, hd1.name, hd2.name and so on.<br><br>For example, the following would indicate there are 2 hydrodynamic files and that they are located in the directory the model is being run from.<br><br>nhdfiles 2<br><br>hd0.name hydrofile1.nc<br><br>hd1.name hydrofile2.nc<br><br>The following indicate the files are stored in the inputs sub-directory (a directory one level down from the run directory)<br><br>hd0.name inputs/hydrofile1.nc<br><br>hd1.name inputs/hydrofile2.nc<br><br>Finally if the inputs folder is in the directory that is at the same level than the run directory then the path to the hydrodynamics files should read as<br><br>hd0.name ../inputs/hydrofile1.nc<br><br>hd1.name ../inputs/hydrofile2.nc<br><br>For more information on how to indicate a path see, for example, this <a href="https://en.wikipedia.org/wiki/Path_%28computing%29">Wikipedia site</a></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Temperature</td>
<td style="text-align: left;">Atlantis can calculate the temperature dynamically, but most models use temperature forcing from more accurate hydrodynamic modes. See chapter 4 for details of temperature forcing files. The lay out of the list of files is as for the hydro file – with as many files listed as given by the ntempfiles parameter.<br><br>use_tempfiles 1 if temperature forcing (NC files) are being used<br><br>ntempfiles N where N is the number of files being provided<br><br>Temperature0.name temp1.nc the path and filename of the first file<br><br>Temperature1.name temp2.nc the path and filename of the second file<br><br>Temperature2.name temp3.nc the path and filename of the third file<br><br>…<br><br>temp_rewind 0 flag indicating whether to rewind (loop over) the temperature forcing data (1) or not (0)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Salinity</td>
<td style="text-align: left;">Atlantis can also load in salinity forcing from more accurate hydrodynamic modes. See chapter 4 for details of salinity forcing files.<br><br>The lay out of the salinity parameters and file name list is as for temperature.<br><br>use_saltfiles 1<br><br>nsaltfiles N<br><br>Salinity0.name salt1.nc<br><br>Salinity1.name salt2.nc<br><br>…<br><br>salt_rewind 0 (or 1)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">pH forcing</td>
<td style="text-align: left;">If pH is tracked, it is possible to calculate it dynamically or provide external forcing values from specific models. The pH forcing is provided through spatial NC files in the same way as for temperature and salinity.<br><br>use_phFiles 0<br><br>npHfiles N<br><br>pH0.name pHforceA.nc<br><br>pH1.name pHforceB.nc<br><br>pH_rewind 0</td>
</tr>
<tr class="even">
<td style="text-align: left;">forcing of other tracers</td>
<td style="text-align: left;">It is possible to force any other tracers with external data. See details on the wiki <a href="https://confluence.csiro.au/display/Atlantis/2013/07/10/Read+in+forcing+data+for+tracers">here</a>. When new data is read in at the end of the timestep any existing value is overwritten with the value from the NC forcing file. This has been used for contaminants and for oxygen (e.g.&nbsp;when internal Atlantis calculations were not reproducing oxygen dynamics sufficiently well). This is a useful option, but should be used with care for any tracers that contains N (and P or C if tracking those tracers), as it can violate the assumption of conservation of matter.<br><br>use_force_tracers 1 (this flag indicates whether additional tracer forcing files should be read it (1) or not (0))<br><br>nforceTracers N (where N is the number of tracers that will be forced)<br><br>tracerNames<br><br>nameA<br><br>nameB<br><br>…<br><br>The list of tracer names (matching the names used in the <em>initial_condition.nc</em> file) that will be forced – with each name on a new line. For example,<br><br>nforceTracers 2<br><br>tracerNames 2<br><br>Oxygen<br><br>Arsenic<br><br>For each tracer listed you must then give the filenames using the format<br><br>TRACERNAME_nFiles N (where TRACERNAME is the name of the tracer and N is the number of files to be loaded)<br><br>TRACERNAME_File0.name TRACER_1.nc (path and filename for the first forcing file for the tracer)<br><br>TRACERNAME_File0.name TRACER_2.nc (path and filename for second file etc)<br><br>TRACERNAME_rewind 0 (whether to rewind the forcing files (1) or not (0))<br><br>for example<br><br>Arsenic_nFiles 1<br><br>Arsenic_File0.name Arsenic.nc<br><br>Arsenic_rewind 0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Point sourcing of nutrients</td>
<td style="text-align: left;">Even though Atlantis calculates internal nutrient dynamics, it is relatively common to force additional nutrient inputs (e.g.&nbsp;from sewage outfalls, river mouth, upwellings etc). For example, the California Current, Guam, Gulf of Mexico and Chesapeake Bay models all use nutrient loading -forcing with nutrient time series (Brand <em>et al.</em> 2007; Ainsworth <em>et al.</em> 2015; Weijerman <em>et al.</em> 2015). While such inputs are mostly used to imitate nutrient inputs from sources clearly outside the model domain (e.g.&nbsp;rivers), they can also be used as a proxy for multi-decadal trends in ocean productivity, even if full multi-decadal oceanographic data is not available and must be ‘looped’.<br><br>Externally forced nutrients sources (or sinks if negative values are given) are provided as TS files<br><br>npointss N (where N is the number of externally supplied point source/sink files)<br><br>For each TS file the following details must be given<br><br>pss0.name XXXX (where XXX is a meaningful name for the point, such as a river name, used so the modeller knows what this point represents; this name is NOT used by Atlantis)<br><br>pss0.location X Y Z (e.g.&nbsp;3951091.3 1789202.7 <strong>-1)</strong><br><br>pss0.data PSSTS1.ts (path and filename of the forcing TS file)<br><br>pss0.rewind 1 (whether to rewind the forcing file (1) or not (0))</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</div>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Caution
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Note!</strong> The location values (X Y Z) has three values – coordinates to input the point source (3951091.3 1789202.7) and the depth <strong>(-1).</strong> To make sure the point source is deposited in the desired box it is a good idea to ensure the X Y values match the “inside” point of the box as given in the BGM file (see chapter 3).</p>
<p>The <strong>last number in the location is very important</strong> as it will determine the correct reading of the forcing data. For point source data the depth must be a negative number for it to be deposited in the water. Other time series forcing files (e.g.&nbsp;for catch) follow a similar format to the PSS files – requiring a name, location, data (filename) and rewind flag. However, <strong>for these forcing files the third number gives the box ID number (from BGM file, see chapter 3) not a depth.</strong></p>
</div>
</div>
<div class="table-responsive">
<div id="tbl-forcing-parameters-2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-forcing-parameters-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Additional forcing parameters for Atlantis model configuration
</figcaption>
<div aria-describedby="tbl-forcing-parameters-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Forcing</strong></th>
<th style="text-align: left;"><strong>Parameters needed in <em>force.prm</em></strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Bottom stress</td>
<td style="text-align: left;">Bottom stress values are used to calculate resuspension and additional macrophyte mortality due to wave action. Atlantis can calculate bottom stress values dynamically, but if processes affected by bottom stress are a focus of the study it is recommended to force stress externally from more precice hydrodynamic models. At present there is no flag to indicate whether this file will be loaded (future releases are likely to switch to a flag as for temperature and salinity, e.g.&nbsp;use_stressfiles). At present if the BottomStress tag is in the <em>force.prm</em> then the listed file will be read automatically.<br><br>BottomStress stress.nc (the path and filename of the stress NC input file).<br><br>If you do not wish to use bottom stress simply omit the BottomStress entry from the <em>force.prm</em> file.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Precipiation and evaporation</td>
<td style="text-align: left;">See chapter 5.2 on how the precipitation forcing data is used. As in case of bottom stress, precipitation and evaporation are forced through spatial NC files. They will be loaded if the tag name is present in the <em>fore.prm</em> file (if not provided the model will not look to load the files).<br><br>Precipitation rain.nc (path and filename for the precipitation)<br><br>Evaporation evap.nc (path and filename for the evaporation)<br><br><strong>These files will not rewind</strong>.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Solar radiation</td>
<td style="text-align: left;">Solar radiation can be calculated dynamically by Atlantis or can be forced through a time series TS file. In the later case (TS file used) the same value is used for the entire model domain. If you do not wish to load a solar TS file do not provide a Solar_radiation entry in <em>force.prm</em> and set lim_sun_hours to 1 in the <em>biology.prm</em> file. As with bottom stress the solar radiation file will be loaded if the tag name is present in the <em>fore.prm</em> file<br><br>Solar_radiation solar.ts (path and filename for the solar forcing file)<br><br>Solar_radiation_rewind 0 (a flag indicating whether to rewind the data file (1) or not (0))</td>
</tr>
<tr class="even">
<td style="text-align: left;">CO2 concentrations</td>
<td style="text-align: left;">Time series of atmospheric CO2 concentrations. This is used to dynamically calculate pH values and is required if trac_pH=1 in <em>run.prm</em>.<br><br>See further details on the wiki <a href="https://confluence.csiro.au/display/Atlantis/2012/10/19/Handling+effects+of+acidification">here</a></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Ice</td>
<td style="text-align: left;">If ice is modelled dynamically, the user must provide ice forcing data. See details on the wiki <a href="https://confluence.csiro.au/display/Atlantis/Ice+Forcing+files">here</a></td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Forcing of ecological parameters</strong></td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Forcing of recruitment</td>
<td style="text-align: left;">Recruitment can be forced in two ways, see details on the wiki <a href="https://confluence.csiro.au/display/Atlantis/Recruitment+forcing">here</a><br><br>The first is to use a single recruitment time series across the entire model domain. To do this the tag Recruitment_time_series must be added to the <em>force.prm</em> file<br><br>Recruitment_time_series filename.ts (path and filename for the time series)<br><br>This time series provides a TS file of recruits entering the entire model domain. Box specific forcing of recruitment is also allowed as described in the link above.<br><br>The second way is to allow for time series of recruitment to be read in for specific boxes. To do this set<br><br>nMultRects N (the number of boxes where recruitment time series will be provide)<br><br>typeMultRects 1 (the type of time series – whether to use the last value (0) or interpolate between values (1))<br><br>The for each of the N boxes you need to provide the following:<br><br>MultRects0.name Meaningful_name<br><br>MultRects0.location X Y BOXID (e.g.&nbsp;4924432.61 3298510.07 94)<br><br>MultRects0.data filename1.ts (path and filename of the TS file for box BOXID)<br><br>MultRects0.rewind 0 (whether to rewind the file (1) or not (0))<br><br>MultRects1.name Meaningful_nameB<br><br>MultRects1.location X Y BOXID2<br><br>MultRects0.data filename2.ts<br><br>MultRects0.rewind 0<br><br>…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Recruitment scaling</td>
<td style="text-align: left;">Recruitment can also be scaled by a time series of species-specific scalars provided in a time series (TS) file. To use this option include the tag<br><br>Recruitment_enviro_forcing in the <em>force.prm</em> file<br><br>Recruitment_enviro_forcing scalarfile.ts (path and filename for the time series)<br><br>More details are given on the <a href="https://confluence.csiro.au/display/Atlantis/Recruitment+forcing">wiki</a></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Recruit size</td>
<td style="text-align: left;">Representing differential survival can be done in two ways, both of which use a time series file. To activate these set flag_modify_KWSR in the <em>biology.prm</em> file to a value greater than 0. In both cases KWRR will be reset so that it is KWSR * X_RS. If flag_modify_KWSR is set to 1 then the model will load a time series of multipliers to apply to the constant KWSR supplied for the group in the <em>biology.prm</em> file. If flag_modify_KWSR is set to 2 then the model will load a time series file of values to use for KWSR.<br><br>In both cases the file for KWSR is supplied in force.prm as follows<br><br>KWSR_forcing KWSR_filename.ts</td>
</tr>
<tr class="even">
<td style="text-align: left;">Larval connectivity matrix</td>
<td style="text-align: left;">To activate set use_larvalfiles 1 in the <em>force.prm</em> and then provide the filename of the connectivity matrix per species using larval dispersal<br><br>Larval0.name connectfile.nc (path and filename for the connectivity matrix NC file)<br><br>Larval_rewind 0 (a flag indicating whether to rewind the file (1) or not (0))<br><br>The NC file must contain an entry XXX_Connnectivity (where XXX is the group code from the <em>functional_groups.csv</em> file). These entries are annual connectivity matrices. If there are les entries than there are years in the run then the rewind flag will dictate whether the file is rewound or not.<br><br>This is recent functionality that has not been widely used. It allows to enter larval dispersal matrix. See further details <a href="https://confluence.csiro.au/display/Atlantis/Recruitment+Options">here</a><br><br>If you want this connectivity matrix to be used completely in place of recruit_hdistrib (rather than in combination with it) then set the flag larvae_connect_only to 1.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Linear mortality scaling</td>
<td style="text-align: left;">External scalar on linear mortality (<em>mortsc</em> in chapters on Ecology routines) – can also be supplied as an additional site specific mortality rate rather than a scalar. This can be provided as a TS file or spatially with box-specific values as an NC file.<br><br>See details <a href="https://confluence.csiro.au/pages/viewpage.action?spaceKey=Atlantis&amp;title=External+Mortality%2C+Growth+and+Recruitment+Scaling">here</a> on how the external mortality scaling is set and calculated.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Scaling of size, growth rate or maturation proportion</td>
<td style="text-align: left;">The scaling of growth and maturation has been used to explore ecological consequences of long-term trends in life-history traits (e.g.&nbsp;Audzijonyte et al.&nbsp;2013; Audzijonyte &amp; Kuparinen 2016).<br><br>The scaling is forced through external forcing scalars on size (SN and RN values), growth rate (mum parameter) or maturation (FSPB parameter). The scalars are applied by scaling the existing values. See further details on size change forcing <a href="https://confluence.csiro.au/display/Atlantis/2010/07/12/Group+size+scale+time+series+input+-+non-compulsory+change+to+forcing+input+file">here</a> and on mum and FSPB scalar <a href="https://confluence.csiro.au/display/Atlantis/2011/03/03/Changing+growth+rates+and+FSPB+over+time">here</a></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</div>
<p><strong><em>Forcing of fisheries and socio-economic parameters</em></strong></p>
<p>It is possible to provide forced catches, discards, effort and other socio-economic parameters. Forced catches and discards, in particular, have been used to parameterise the model and emergent biomasses given the known catch history. See, for example, details in <a href="https://confluence.csiro.au/display/Atlantis/Useful+Reading?preview=/43155482/341447378/Link_et_al_2011_NEUS_tech_memo.pdf">Fulton et al.&nbsp;2007 and Link et al.&nbsp;2011</a>. The catch and discard forcing files are provided as box-specific species-specific time series. At each timestep Atlantis will then take the forced catch from the species biomass. See further details in the description of the Harvest submodel.</p>
<div class="table-responsive">
<div id="tbl-fisheries-forcing" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-fisheries-forcing-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: Fisheries forcing parameters for Atlantis model configuration
</figcaption>
<div aria-describedby="tbl-fisheries-forcing-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 74%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Forcing</strong></th>
<th style="text-align: left;"><strong>Parameters needed in <em>force.prm</em></strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Catch</td>
<td style="text-align: left;">To force catches use the following parameters<br><br>nCatchts N (where N is the number of catch force time series (TS) files)<br><br>typeCatchts 1 (whether to use the last value (1) or interpolate (0) between the two forcing time steps)<br><br>This is followed by the actual box-specific forcing file information. Atlantis will attempt to take the forced catch from the specified box. If not enough biomass is available Altnaits will first try to take the biomass form younger age classes, then may look to neighbouring boxes (depending on the flagimposecatch setting in <em>harvest.prm</em>) and if it still can’t fill it will hold it over (“carry over”) and add the remaining amount to the biomass to take the following day. If at the end of the year there still remains catch that cannot be taken it is noted in the <em>log.txt</em> file and the “carry over catch” is zeroed to start again in the new year.<br><br>Catchts0.name meaningful_name (e.g.&nbsp;box0catch; this is NOT used by Atlantis)<br><br>Catchts0.location X Y BOXID (e.g.&nbsp;e.g.&nbsp;370889.3287 -717418.8373 0. This is the x, y and box ID indicating the box where the catch will be extracted. It is safest to use the “inside” point of the box BOXID as given in the BGM file - see chapter 3 on details about model geometry)<br><br>Catchts0.data catchfile1.ts (path and filename of the catch TS file)<br><br>Catchts0.rewind 0 (whether to rewind the data file (1) or not (0))</td>
</tr>
<tr class="even">
<td style="text-align: left;">Discard</td>
<td style="text-align: left;">The entry format is as for catches above, but instead of catches provide discard values for the specified boxes<br><br>nDiscardts N (where N is the number of time series (TS) files)<br><br>typeDiscardts 1 (whether to use the last value (1) or interpolate (0) between the two forcing time steps)<br><br>Discardts0.name meaningful_name<br><br>Discardts0.location X Y BOXID<br><br>Discardts0.data disfile1.ts (path and filename of the TS file)<br><br>Discardts0.rewind 0 (whether to rewind the data file (1) or not (0))</td>
</tr>
<tr class="odd">
<td style="text-align: left;">MPA</td>
<td style="text-align: left;">This forcing file “closes” a proportion of the box to fishing (with the columns in the TS file being the closure per fishery), simulating marine protected areas (MPA). This is used in place of the MPA vectors in <em>harvest.prm</em> and is useful where MPAs vary through time. Further details are provided in the Harvest submodel description<br><br>nMPAts N (where N is the number of time series (TS) files)<br><br>typeMPAts 1 (whether to use the last value (1) or interpolate (0) between the two forcing time steps)<br><br>MPAts0.name meaningful_name<br><br>MPAts0.location X Y BOXID<br><br>MPAts0.data mapfile1.ts (path and filename of the TS file)<br><br>MPAts0.rewind 0 (whether to rewind the data file (1) or not (0))</td>
</tr>
<tr class="even">
<td style="text-align: left;">Effort</td>
<td style="text-align: left;">This forcing file provides the effort time series to apply in a box (with the columns of the TS file giving the effort per fishery) Further details are provided in the Harvest submodel description<br><br>nEffortts N (where N is the number of time series (TS) files)<br><br>typeEffortts 1 (whether to use the last value (1) or interpolate (0) between the two forcing time steps)<br><br>Effortts0.name meaningful_name<br><br>Effortts0.location X Y BOXID<br><br>Effortts0.data effortfile1.ts (path and filename of the TS file)<br><br>Effortts0.rewind 0 (whether to rewind the data file (1) or not (0))</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Residuals</td>
<td style="text-align: left;">These time series provide the price residuals per market if using the economics model and forcing historical prices. One time series is required per market, with the columns providing the residual values per species.<br><br>nResidualts N (where N is the number of time series (TS) files)<br><br>typeResidualts 1 (whether to use the last value (1) or interpolate (0) between the two forcing time steps)<br><br>Residualts0.name market_name (NOT used by Atlantis)<br><br>Residualts0.location X Y BOXID (x,y location and box ID for the port which supplies the market)<br><br>Residualts0.data resid_file1.ts (path and filename of the TS file)<br><br>Residualts0.rewind 0 (whether to rewind the data file (1) or not (0))</td>
</tr>
<tr class="even">
<td style="text-align: left;">Economic statistics</td>
<td style="text-align: left;">Economic statistics include GDP and fuel costs. They are used in the economically driven dynamic fishing calculations. They are not box specific, but just time series values that apply across the entire model.<br><br>nEconts 1 (typically 1 or 0; only non-zero if using the economic effort model)<br><br>typeEconts 0 (whether to use the last value (1) or interpolate (0) between the two forcing time steps)<br><br>Econts0.name meaningful_name (NOT used by Atlantis)<br><br>Econts0.location X Y BOXID (x, y and box ID of any dynamic box in the model; by convention set to the values for the box with the larget market port)<br><br>Econts0.data econ_file1.ts (path and filename of the TS file)<br><br>Econts0.rewind 0 (whether to rewind the data file (1) or not (0))</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</div>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Caution
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Note!</strong> Remember that the third number of the location is the box ID number (from BGM file, see chapter 3). <strong>It is very important to give this number correctly or else Atlantis will not read or apply the forcing inputs correctly.</strong></p>
</div>
</div>
<p>: <span id="_Toc526762764" class="anchor"></span>Table 12. List and description of external forcing options available in Atlantis</p>



</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>